thingsboard/thingsboard.github.io

- docs/user-guide/install/config.md
hey, the config path for configuration on linux systems is wrong.
the correct path is not in init.d directory
> fix linux config path

- docs/iot-gateway/integration-with-telegram-bot.md
Because all the docs about the Java gateway were cleared, probably, docs which were included about the telegram bot integration was cleared too. They've stated in the "IoT gateway" folder.
> Got back telegram how to implement guide

- docs/user-guide/install/docker.md
- docs/user-guide/install/pe/docker.md
Instructions to run docker (tb, tb-postgres and tb-cassandra) on Linux without root access
> Run docker without 'root'

- _data/guides-data.yml
- _data/installation.yml
https://thingsboard.io/docs/user-guide/install/aws/
https://thingsboard.io//docs/user-guide/install/cluster/aws-cluster-setup/
https://thingsboard.io//docs/user-guide/install/cluster/aws-self-hosted-setup/
https://thingsboard.io/docs/guides/
https://thingsboard.io/docs/installation/
https://thingsboard.io/docs/user-guide/install/installation-options/
> Aws doc cloud

- docs/reference/rest-api.md
Hello
Here's the current typo:
> fix(rest-api): type resonse → response

- docs/user-guide/troubleshooting.md
I spent a while hunting the metrics path down by reviewing logs. Only references to Prometheus I could see were in release notes and configuration files themselves so I just added it to the docs. 
Please review!
> Add instructions to enable and access prometheus metrics

- docs/user-guide/certificates.md
- docs/user-guide/mqtt-over-ssl.md
fixed an issue
updated examples for SSL certificate generation according to the downloadable resource https://raw.githubusercontent.com/thingsboard/thingsboard/master/tools/src/main/shell/keygen.properties
affected pages:
https://thingsboard.io/docs/user-guide/certificates/
https://thingsboard.io/docs/user-guide/mqtt-over-ssl/
> fixed keygen.properties examples for SSL certificate generation

- _includes/templates/install/timescale-rhel-install.md
- _includes/templates/install/timescale-ubuntu-install.md
- _includes/templates/install/timescale-windows-install.md
Previously, instruction for Timescale regarding extension installation was very subtle (you needed to find a post-install page, and it was unclear on how to do it on WIndows).
> Add TimescaleDB extension installation instructions

- docs/user-guide/contribution/how-to-contribute.md
- docs/user-guide/install/building-from-source.md
build from sources skip tests, docker required for some tests, tips and tricks to boost build experience.
This PR is related to integration tests that required docker and docker-compose https://github.com/thingsboard/thingsboard/pull/5383
> build from sources skip tests, docker required for some tests, tips and tricks to boost build experience

- README.md
- pull_request_template.md
Use the following command to check the broken links.
```bash
```
> linkchecker docker run simplify

- _includes/docs/reference/performance-aws-instances.md
This is the minor fix of the m6a.2xlarge instance in the summary table
Affected page: https://thingsboard.io/docs/reference/performance-aws-instances/
```bash
```
> fixed description: m6a.2xlarge: 8 vCPU, 32GB RAM

- _includes/templates/provisioning/coap-access-token-credentials-type.md
- _includes/templates/provisioning/coap-without-credentials-type.md
- _includes/templates/provisioning/http-access-token-credentials-type.md
- _includes/templates/provisioning/http-without-credentials-type.md
- _includes/templates/provisioning/without-credentials-type.md
This PR contains small fixes for HTTP client (default port changed) and different library for python example scripts for device provisioning.
```bash
```
> Fix for provisioning example clients

- _includes/docs/reference/mqtt-api.md
I think there is an error in the [MQTT firmware API reference](https://github.com/thingsboard/thingsboard.github.io/blob/007422a3c3585529d2d743cc8885ecc0b05e510b/_includes/docs/reference/mqtt-api.md?plain=1#L313). Judging from the [python MQTT firmware example](https://github.com/thingsboard/thingsboard.github.io/blob/master/docs/user-guide/resources/firmware/mqtt_firmware_client.py), the firmware chunk request's topic should contain the chunk index and its payload should be the chunk size.
> fix MQTT firmware API reference doc

- docs/user-guide/install/building-from-source.md
The root cause is file line ending. Windows uses CRLF, Unix - LF.
My Git client automatically switches line endings while cloning or committing sources, but to locally build Docker image some sources need to have LF ending otherwise TB will not be able to start.
And please don't leave your Dart client [PR](https://github.com/thingsboard/dart_thingsboard_client/pulls) and [issues](https://github.com/thingsboard/dart_thingsboard_client/issues) alone)))
> [3.4] Explain how to configure the Git repo to build Docker image on Windows.

- docs/pe/reference/dart-client.md
Fix for broken include link for dart client.
Issue - https://github.com/thingsboard/thingsboard.github.io/issues/894
```bash
```
> Fix for wrong dart client link

- docs/iot-gateway/install/docker-windows.md
Fix for docker run command for the gateway, running on windows.
Related issue - https://github.com/thingsboard/thingsboard/issues/7737
```bash
```
> Fix for docker command arguments

- _includes/partners.json
Changed Teltonika networks home URL
```bash
```
> Teltonika home link

- _includes/docs/user-guide/install/config.md
add SQL configuration parameters for cleanup audit log events by TTL
added: 
- sql.ttl.audit_log.enabled
- sql.ttl.audit_log.events_ttl
- sql.ttl.audit_log.execution_interval_ms
```bash
```
> [3.5] implement cleanup event by TTL for audit log

- _data/guides-data.yml
On the **Guides** page -> **Connect your device** -> **Devices uses UDP protocol** fixed UDP integration documentation link
https://thingsboard.io/docs/pe/guides/#AnchorIDConnectYourDevice
```bash
```
> fixed UDP integration documentation link

- _includes/docs/user-guide/rule-engine-2-0/ce-filter-nodes.md
Replacing the wrong image to show the Entity type filter node config UI.
```bash
```
> FIX: Entity type filter rule node image

- _includes/devicelibrary.html
- _includes/devices.liquid
- _includes/docs/devices-library/index.md
- _layouts/devices-library-article.liquid
- _sass/_base.sass
- _sass/_code-styles.sass
- _sass/_desktop.sass
- _sass/_tablet.sass
- docs/devices-library.sass
Added option to expand/collapse code blocks:
Collapsed code:
Expanded code:
> Fixed alignment of devices titles, temporary hidden filters on smaller screens

- _includes/templates/install/docker/docker-create-folders-sudo-explained.md
- docs/user-guide/install/edge/docker.md
- docs/user-guide/install/pe/edge/docker.md
> Remove edge related stuff from CE/PE TB docker installations

- _includes/templates/ssl/certificates-chain.md
- _includes/templates/ssl/certificates-leaf.md
- docs/paas/user-guide/certificates.md
PAAS: Add documentation for X.509 Certificate chain authentication and auto-provisioning over MQTT.
Replace tb-server-chain.pem usages on cloud into tb-cloud-chain.pem
```bash
```
> Feature/X509 device provisioning: cloud

- _includes/docs/user-guide/contribution/widgets-development.md
In [Alarm widget section](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#alarm-widget) Javascript code should be changed from: 
`var pageLink = self.ctx.pageLink();` to `var pageLink = self.ctx.pageLink(100);` in order to fetch alarms data in a proper way.
- https://thingsboard.io/docs/user-guide/contribution/widgets-development
```bash
```
> Widget Development Guide. Fix in Alarm widget to fetch alarms correctly

- _includes/docs/reference/coap-api.md
> Fixed commands in the CoAP Device API Reference (CE, PE and PAAS)

- _includes/templates/helloworld-pe/http.md
> Replaced 'https' with 'http' in the http command

- README.md
When the repository is deployed in a docker without a previous run in the OS environment, the startup fails:
Solution: add a `PAGES_REPO_NWO` variable that specifies the name of the repository. By default: `thingsboard/thingsboard.github.io`
```bash
```
> Add PAGES_REPO_NWO env

- _includes/templates/prerequisites.md
Changed port from **9090** to **8080** in this commands:
```
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs
docker run -it -p 8080:9090 -p 7070:7070 -p 1883:1883 -p 5683-5688:5683-5688/udp -v ~/.mytb-data:/data \
-v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb-postgres
```
```bash
```
> Getting Started CE doc. Edited command for docker

- _data/gw/docs-home.yml
Fixed Getting-started link underlining in IoT-Gateway when this route is active
```bash
```
> Fixed Getting-started link underlining in IoT-Gateway

- _includes/docs/user-guide/tbel.md
The hex value "BBAA" is initially converted to the Int data type ([-69, -86]), not Unsigned Int ([187, 170]).
> Change values for "hexToBytes" and "bytesToHex" examples

- pull_request_template.md
> Check list removed in favour of automated check by the build agent

- _config.yml
- _includes/docs/mobile/getting-started.md
- _includes/docs/pe/reference/dart-client.md
- docs/reference/dart-client.md
The documentation updated the current version of the Dart client and Flutter ThingsBoard Mobile compatibility matrix
```bash
```
> Update Flutter ThingsBoard Mobile compatibility matrix to latest version 

- _config.yml
- _includes/docs/mobile/getting-started.md
- _includes/docs/pe/reference/dart-client.md
- docs/reference/dart-client.md
The documentation updated the current version of the Dart client and Flutter ThingsBoard Mobile compatibility matrix
```bash
```
> Update Flutter ThingsBoard Mobile compatibility matrix to latest version

- docs/user-guide/install/pe/docker.md
When using "sudo sh -c", tilde (~) expands into "/root" instead of the user home directory.
Simple test : ```sudo sh -c "echo ~"```
To get the user home directory with "sh", the tilde must be replaced with the $HOME variable. Alternatively, use a simpler command with "tee".
Affected documentation section: https://thingsboard.io/docs/user-guide/install/pe/docker/#upgrade-starting-from-310pe 
```bash
```
> Fix command to specify ".upgradeversion" for docker

- _includes/docs/user-guide/install/how-to-change-config.md
- docs/user-guide/install/pe/config.md
1. The documentation updated for:
- https://thingsboard.io/docs/user-guide/install/how-to-change-config/
- https://thingsboard.io/docs/user-guide/install/pe/how-to-change-config/
Non-existing links with anchors #configuration-parameters were replaced with links to the appropriate CE and PE pages with config parameters.
2. Added redirect  
from  
https://thingsboard.io/docs/pe/user-guide/install/config/  
to  
https://thingsboard.io/docs/user-guide/install/pe/config/
```bash
```
> Fix broken links on CE & PE Configuration pages

- docs/edge/reference/coap-api.md
- docs/edge/reference/mqtt-api.md
- docs/pe/edge/reference/coap-api.md
- docs/pe/edge/reference/mqtt-api.md
> Edge MQTT/CoAP API uses CE/PE doc prefix

- _includes/docs/user-guide/device-profiles.md
The documentation updated for:
- https://thingsboard.io/docs/user-guide/device-profiles/
- https://thingsboard.io/docs/pe/user-guide/device-profiles/
- https://thingsboard.io/docs/paas/user-guide/device-profiles/
List of changes:
- Fixed examples of typical MQTT commands (with default topics)
- Added separate MQTT command examples with custom topics
- hostname in commands for CE and PE demo.thingsboard.com was replaced with a variable (similar to other pages)
```bash
```
> Fix example commands for MQTT device topic filters

- _includes/docs/edge/user-guide/grpc-over-ssl.md
- _includes/templates/edge/user-guide/grpc-over-ssl-build-in.md
- _includes/templates/edge/user-guide/grpc-over-ssl-load-balancer.md
- _includes/templates/edge/user-guide/grpc-over-ssl-rhel.md
- _includes/templates/edge/user-guide/grpc-over-ssl-ubuntu.md
> Added steps to configure edge ssl using build-in platform mechanism

- _includes/docs/pe/user-guide/integrations/remote-integrations.md
"_includes/templates/install/integration/coap-rhel.md" file have been present since https://github.com/thingsboard/thingsboard.github.io/pull/713 but it was unused due to the missing "include".
- https://thingsboard.io/docs/user-guide/integrations/remote-integrations/#centosrhel-server
- https://thingsboard.io/docs/paas/user-guide/integrations/remote-integrations/#centosrhel-server
```bash
```
> Expose "CoAP Integration" option for CentOS/RHEL Server

- _includes/templates/install/ubuntu-queue-kafka.md
Fixed an incorrect move command from https://github.com/thingsboard/thingsboard.github.io/pull/1298
- https://thingsboard.io/docs/user-guide/install/ubuntu/
- https://thingsboard.io/docs/user-guide/install/pe/ubuntu/
```bash
```
> Fixed Kafka installation command in Ubuntu instructions

- _includes/docs/user-guide/tbel.md
https://thingsboard-portal.atlassian.net/browse/PROD-3409
```
The encodeURI() function escapes characters by UTF-8 code units, with each octet encoded in the format %XX, left-padded with 0 if necessary. Because lone surrogates in UTF-16 do not encode any valid Unicode character, they cause encodeURI() to throw a [URIError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError).
```
> tbe_encodeURI_decodeURI

- _data/paas/guides-data.yml
- _data/pe/guides-data.yml
- _includes/docs/guides.md
- docs/guides.md
- docs/paas/guides.md
- docs/pe/guides.md
- Fixed the dashboard's guide link in the Guides page;
- Fixed switching between CE, PE, and PAAS versions of the site.
```bash
```
> Fixed dashboard's guide link in Guides page

- _includes/templates/install/create-tb-db-rhel.md
- _includes/templates/install/memory-on-slow-machines.md
- _includes/templates/install/postgres-install-rhel.md
- _includes/templates/install/windows-memory-on-slow-machines.md
- docs/user-guide/install/pe/rhel.md
- docs/user-guide/install/pe/ubuntu.md
- docs/user-guide/install/pe/windows.md
- docs/user-guide/install/rhel.md
- docs/user-guide/install/rpi.md
- docs/user-guide/install/ubuntu.md
- docs/user-guide/install/windows.md
Updated Ubuntu. RHEL, Raspberry and Windows, CE and PE.
- RHEL - updated versions from 7/8 to 8/9; refactored changes according to the changes in new OS and packages
-- tested on RHEL 8/9, CentOS Stream 8/9, Oracle 9, Alma 9, Rocky 9, Fedora 38/39
- Ubuntu - updated versions from 18/20 to 20/22
- Windows - updated versions from 10/8/7 to 11/10, removed mention of 32-bit arch
- All monoliths installs - changed min recommended RAM from 1GB to 4GB; updated Xms Xmx JAVAOPTS optional step accordingly (2G); change "please wait up to 90 secs for UI to startup" to not mention slow machines
```bash
docker run --rm -it --network=host …
```
> update and refactor monolith installation guides

- _includes/docs/reference/lwm2m-api.md
Add a note about LwM2M object versions. It would have helped avoid corresponding pitfalls.  Others seem to have had those problems as well.
See https://github.com/thingsboard/thingsboard/issues/6179
The documentation updated for LwM2M Device API Reference includes a note making people aware that LwM2M object versions must be considered, when uploading LwM2M models.
```bash
```
> Add a note about LwM2M object versions.

- docs/devices-library/ace-iot-gateway-and-siemens-logo.md
- docs/devices-library/teltonika-rut955-and-siemens-logo.md
- docs/paas/devices-library/ace-iot-gateway-and-siemens-logo.md
- docs/paas/devices-library/teltonika-rut955-and-siemens-logo.md
- docs/pe/devices-library/ace-iot-gateway-and-siemens-logo.md
- docs/pe/devices-library/teltonika-rut-955-and-siemens-logo.md
Before fix:
After fix:
```bash
```
> Remove duplicete filter WiFi for device library

- _includes/templates/install/tb-370-update-linux.md
- _includes/templates/install/tb-370-update-windows.md
- docs/user-guide/install/pe/resources/3.7pe/thingsboard-centos-download.sh
- docs/user-guide/install/pe/resources/3.7pe/thingsboard-centos-installation.sh
- docs/user-guide/install/pe/resources/3.7pe/thingsboard-ubuntu-download.sh
- docs/user-guide/install/pe/resources/3.7pe/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/resources/3.7/thingsboard-centos-download.sh
- docs/user-guide/install/resources/3.7/thingsboard-centos-installation.sh
- docs/user-guide/install/resources/3.7/thingsboard-ubuntu-download.sh
- docs/user-guide/install/resources/3.7/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/upgrade-instructions.md
added upgrade instructions for 3.7, with the warning note about migration to Java 17
minor typo fix in v3.6.4 upgrade for Windows (package was referred to v3.6.3) as well
```bash
```
> upgrade instructions for 3.7

- docs/user-guide/install/docker-windows.md
- docs/user-guide/install/docker.md
Old images (`tb` and `tb-cassandra`) for monolith CE Docker installations were removed.
```bash
```
> remove legacy options for CE monolith docker setups

- docs/user-guide/install/pe/docker-windows.md
- docs/user-guide/install/pe/docker.md
Upgrade instructions for monolith PE Docker installations were rewritten for more clarity.
```bash
```
> refactor upgrade instructions for PE monolith docker setups

- _includes/templates/integration/particle/particle-downlink-js.md
- _includes/templates/integration/particle/particle-downlink-tbel.md
Example of doenlink converter for Particle integration contained wrong field name that cause the issue that integration throws error that field is wrong and required field is absent.
```bash
```
> Fix for particle integration downlink converter example

- _includes/docwithnav.html
- _includes/head-header.html
- _sass/_docs.sass
- docs/mobile/search.md
- docs/pe/mobile/search.md
- products/thingsboard-pe/index.md
- products/thingsboard-pe/thingsboard-pe.sass
- Fixed 'Products Dropdown' displays over 'Products Pop-up'
- Fixed search for Edge PE, Mobile and Mobile PE products page.
- Fixed duplicate id for Thingsboard PE page.
> Minor fixes for site and documentation

- docs/user-guide/install/pe/upgrade-instructions.md
Added a step guiding to license key configuration for "CE to PE" upgrade instructions.
```bash
```
> add license key step for ce-to-pe upgrade

- docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm.md
Updated the /docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/ page. This closes https://github.com/thingsboard/thingsboard.github.io/issues/441
> Fix wrong number in create-inactivity-alarm.md

- _includes/templates/install/rhel-webreport-docker.md
- _includes/templates/install/rhel-webreport-service.md
- _includes/templates/install/ubuntu-webreport-docker.md
- _includes/templates/install/ubuntu-webreport-service.md
- _includes/templates/install/webreport-docker.md
- docs/user-guide/install/aws-marketplace-pe-upgrade.md
- docs/user-guide/install/pe/rhel.md
- docs/user-guide/install/pe/ubuntu.md
The documentation for the WebReport component was updated to allow the installation of this service as the docker container. Also, I updated the link for the notosans fonts, as the previous source no longer exists. 
```bash
```
> Add dockerized web report

- docs/reference/releases.md
> Fixed broken Gateway dashboard improvements PRs link in 3.8.0 release  notes

- _includes/templates/install/rhel-webreport-docker.md
- _includes/templates/install/ubuntu-webreport-docker.md
- _includes/templates/install/ubuntu-webreport-service.md
- docs/user-guide/install/aws-marketplace-pe-upgrade.md
The documentation updated for the ubuntu web report service installation. Deleted libraries (gconf-service libasound2 libgconf-2-4 libappindicator1) that are no longer accessible in ubuntu 24.04 and caused fail of apt install command (no other required packages were installed). Also minor fixes for webreport in docker installation. 
```bash
```
> Web report fix

- _includes/templates/install/docker-queue-kafka.md
- _includes/templates/install/pe-docker-queue-kafka.md
- _includes/templates/install/queue-kafka-in-docker.md
- _includes/templates/install/ubuntu-queue-kafka.md
- _includes/templates/install/windows-docker-queue-kafka.md
- _includes/templates/install/windows-pe-docker-queue-kafka.md
Current [link](https://downloads.apache.org/kafka/3.6.2/kafka_2.13-3.6.2.tgz) for kafka in documentation returns 404. Changed to a new one, and updated kafka docker image version as well for consistency.
```bash
```
> Change kafka version to 3.8.1 in install guides

- _data/edge-pe/docs-home.yml
- _data/edge/docs-home.yml
- docs/edge/config/create-device.md
- docs/pe/edge/config/create-device.md
Article name fix:
-Title fixed from "Device Creation and Cloud Provisioning" to "Device Management"
-article description fixed
```bash
```
> Article name fix

- _includes/docs/devices-library/blocks/microcontrollers/raspberry-pi-pico-arduino-library-install-block.md
- _includes/docs/devices-library/blocks/microcontrollers/thingsboard-arduino-library-install-block.md
The documentation was updated for Device Library -> Raspberry Pi Pico W. 
If you follow the step-by-step guide, the firmware couldn't compile due to missing libraries. Steps were added to install those libraries in Arduino IDE.
```bash
```
> Added arduino libraries to Raspberry Pi Pico W guide

- docs/user-guide/resources/firmware/mqtt_firmware_client.py
The documentation for the MQTT OTA example script has been updated. Previously, custom port was retrieved via **input()** function which returns **str** object, after that paho library checks if the **port <= 0** which throws an exception because it's not possible to compare string with integer. Also, fixed variable names to be consistent.
```bash
```
> fixed port typecasting

- docs/user-guide/install/pe/docker-windows.md
- docs/user-guide/install/pe/docker.md
Updated instructions for Docker Monolith PE installs (Linux and Windows) - specify required actions depending on the upgrade version.
```bash
```
> Update docker monolith upgrade instructions for 3.9.1 release

- docs/user-guide/install/cluster/aws-microservices-setup.md
- docs/user-guide/install/cluster/aws-monolith-setup.md
- docs/user-guide/install/cluster/azure-microservices-setup.md
- docs/user-guide/install/cluster/azure-monolith-setup.md
- docs/user-guide/install/cluster/gcp-microservices-setup.md
- docs/user-guide/install/cluster/gcp-monolith-setup.md
- docs/user-guide/install/cluster/minikube-cluster-setup.md
- docs/user-guide/install/cluster/openshift-cluster-setup.md
- docs/user-guide/install/pe/cluster/aws-microservices-setup.md
- docs/user-guide/install/pe/cluster/aws-monolith-setup.md
- docs/user-guide/install/pe/cluster/azure-microservices-setup.md
- docs/user-guide/install/pe/cluster/azure-monolith-setup.md
- docs/user-guide/install/pe/cluster/gcp-microservices-setup.md
- docs/user-guide/install/pe/cluster/gcp-monolith-setup.md
- docs/user-guide/install/pe/cluster/minikube-cluster-setup.md
The documentation has been updated for k8s installation guides since thingsboard-pe-k8s now have different naming for release branches. Also fixed excess space for aws-monolith guide. 
```bash
```
> Changed variable for branch name, minor changes

- _includes/docs/pe/user-guide/domains.md
Added new note to the Domains page: 
Starting from ThingsBoard version 3.9.0, adding your own domain name is available at both the Tenant level and the Customer level.
PE:
PAAS / EU PAAS:
```bash
```
> Added new note to the Domains doc page

- docs/user-guide/install/upgrade-instructions.md
Fix upgrade instructions package versions from 3.9 to 3.9.1 in the 3.9.1 CE guide section
```bash
```
> Fix upgrade instructions package versions in 3.9.1 CE guide

- _layouts/devices-library-article.liquid
Before fix:
After fix:
```bash
```
> Fixed color for device library article pages

- _includes/docs/pe/user-guide/integrations/mqtt.md
- _includes/docs/user-guide/mqtt-retransmission-mechanism.md
- _includes/docs/user-guide/rule-engine-2-0/ce-external-nodes.md
The documentation updated for MQTT integration and MQT node doc. Now includes explanation of how MQTT retransmission mechanism works.
```bash
```
> Mqtt retransmission doc

- docs/user-guide/install/building-from-source.md
- Updated the Java version requirement from 11 to 17 and fixed link.
- Changed Git clone command to HTTPS: Replaced the SSH-based clone URL because cloning via SSH can fail due to missing public key access (Permission denied (publickey)). Users outside the organization may not be able to clone the repository via SSH.
- Other general improvements and cleanup.
```bash
```
> Fix build from source guide

- _includes/docs/reference/gateway-mqtt-api.md
The documentation updated for Gateway MQTT when connecting to include the `type` in the message. This already allows setting the device profile when connecting, but no documentation exists for this yet.
Explained that the type is optional and uses `default` if none is sent.
```bash
```
> Update gateway connect documentation to include type

- _includes/docs/pe/user-guide/install/coap-transport-config.md
- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/ie-executor-config.md
- _includes/docs/pe/user-guide/install/lwm2m-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/pe/user-guide/install/snmp-transport-config.md
- _includes/docs/reference/msa.md
- _includes/docs/user-guide/attributes.md
- _includes/docs/user-guide/install/coap-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/lwm2m-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/snmp-transport-config.md
- _includes/docs/user-guide/troubleshooting.md
Valkey is a drop-in replacement for Redis.
According to PR's from S Matvienko(https://github.com/thingsboard/thingsboard/pull/12925/ and https://github.com/thingsboard/thingsboard-pe-docker-compose/pull/68), Thingsboard supports Valkey as a Cache Database. 
Thus, this PR adds Valkey reference where Redis is mentioned in the ThingsBoard documentation.
The documentation updated for: 
- config parameters
- MSA reference
- troubleshooting page
- attributes page
```bash
```
> Add Valkey reference where Redis mentioned

- _includes/docs/pe/user-guide/custom-menu.md
- _includes/docs/pe/user-guide/custom-translation.md
- _includes/docs/pe/user-guide/white-labeling.md
Video tutorial links have been added for the following guides:
- White labeling
- Custom translation
- Custom menu
```bash
```
> Added a links to a video guides

- README.md
- docker-compose.yaml
The docker-compose.yaml file included in the `README.md` to be moved into the repository, to allow easy building and launching of the website.
Documentation in the `README.md` updated to use the docker-compose.yaml file without the requirement to add it.
If you don't want to include this you can decline this pull request.
```bash
```
> Include docker compose file in repository

- docs/user-guide/install/docker-windows.md
- docs/user-guide/install/pe/docker-windows.md
The documentation has been updated for the Windows Docker guide.
```bash
```
> Removed exit code check for windows docker guide

- _includes/templates/edge/install/cassandra-rhel-install.md
- _includes/templates/edge/install/cassandra-ubuntu-install.md
- _includes/templates/install/rhel-java-install.md
- _includes/templates/install/ubuntu-java-install.md
- docs/mqtt-broker/install/building-from-source.md
- docs/user-guide/install/resources/java-centos-installation.sh
- docs/user-guide/install/resources/java-ubuntu-installation.sh
[openjdk-11-jdk-headless](https://github.com/thingsboard/thingsboard.github.io/commit/cb6be4b2a69ff4bb45419cf13557f1ba05a776a5) 
[openjdk-17-jdk-headless](https://github.com/thingsboard/thingsboard.github.io/commit/7e32dc292a975f2e58474c9298779f4b6102c942)
[dnf install java-17-openjdk-headless](https://github.com/thingsboard/thingsboard.github.io/pull/2102/commits/4d6cef66a37ed4db440e268a024e8477e601331c) 
[yum install java-11-openjdk-headless](https://github.com/thingsboard/thingsboard.github.io/pull/2102/commits/aa3d7cffa6e6458f50068d0bd0321e3b4e3a60ea)
Windows install with no change because it references to JDK web page install
Recheck across all over the project
You can use the following …
> JDK headless

- docs/user-guide/install/pe/docker-windows.md
- docs/user-guide/install/pe/docker.md
- docs/user-guide/install/pe/old-docker-migrate-windows.md
- docs/user-guide/install/pe/old-docker-migrate.md
The documentation has been updated for Docker monolith guides (Linux, macOS, and Windows). Added new pages with steps on how to move from old directory binds and external volumes to the current deployment files structure. 
```bash
```
> Added migration guide for old Thingsboard PE docker-compose deployment files.

- _data/pages_info.yml
- _data/pages_redirect_info.yml
- docs/user-guide/rule-engine-2-0/nodes/external/aws-sqs.md
Fixed typo in link for redirecting outdated SQS plugin guide to SQS rule node.
Additionally, when generating site, some Gateway links were fixed with auto-generated redirect YAML file - they are also included in this PR.
```bash
```
> fix redirects for SQS and Gateway

- _includes/docs/user-guide/telemetry.md
This PR updates the documentation for the ThingsBoard data retention policy. The current version does not provide a detailed explanation of the available features.
This PR improves the data retention section to make the explanation clearer.
How it was:
How it became:
```bash
```
> Improve data retention description

- _data/pages_info.yml
- _data/pages_redirect_info.yml
- docs/user-guide/ui/security-settings.md
This PR fixes a 404 redirect issue for the Security page: [JWT Security Settings](https://thingsboard.io/docs/user-guide/ui/jwt-security-settings/)
- Corrected a typo in the documentation security settings page that caused the page to return a 404 error when accessed. 
- The following entry in `pages_info.yml` was added when auto-generating site info (it might have been missing from some previous commits)
```yml
"/docs/iot-gateway/guides/how-to-use-rpc-modbus-connector/":
url: "/docs/iot-gateway/guides/how-to-use-rpc-modbus-connector/"
redirect_from: []
```
> Fix redirect issue for security settings page
