- docs/user-guide/contribution/how-to-contribute.md
This tidbit would have saved me a few days of mucking around.
> Add notes for installing under Windows

- _includes/templates/enable-postgresql.md
- docs/user-guide/install/building-from-source.md
I've installed TB several times, and always get hung up here!  I know others have as well.
> Clarify instructions

- docs/user-guide/contribution/how-to-contribute.md
Things I noticed after rebuilding my machine and reinstalling from scratch.
> Improvements

- docs/user-guide/rule-engine-2-0/re-getting-started.md
Minor improvements to documentation; mostly grammar and phrasing
> Minor edits

- docs/iot-gateway/modbus.md
The docs for [Modbus RPC gateway feature](https://github.com/thingsboard/thingsboard-gateway/pull/155).
> Add description of Modbus RPC feature.

- docs/samples/esp32/ota.md
- docs/samples/esp32/resources/ota_for_esp32.json
The changes are taken from https://github.com/thingsboard/thingsboard.github.io/pull/183
but with fixed line endings.
> Fix widget reference in dashboard, text update

- docs/samples/arduino/resources/arduino-dht-esp8266-mqtt.ino
- docs/samples/arduino/temperature.md
Originally reviewed in https://github.com/forGGe/thingsboard.github.io/pull/5
> Update arduino-dht-esp8266 guide

- docs/samples/esp8266/resources/esp8266-dht-mqtt.ino
- docs/samples/esp8266/temperature.md
Do not merge: review by @forGGe is pending.
> Replace PubSubClient library with ThingsBoard SDK

- docs/iot-gateway/all_configuration.md
- docs/iot-gateway/config/mqtt.md
- docs/iot-gateway/configuration.md
- docs/iot-gateway/getting-started.md
- docs/iot-gateway/install/deb-installation.md
- docs/iot-gateway/installation.md
Added getting started and some refactored data.
> IoT Gateway documentation

- docs/user-guide/contribution/widgets-development.md
Hi
Just a few typos I found while reading this document.
> fix: correct words in widgets development guide

- _data/docs-home.yml
- _data/iot-gateway.yml
- docs/iot-gateway/config/can.md
- docs/iot-gateway/configuration.md
- docs/iot-gateway/getting-started.md
- docs/iot-gateway/index.md
- docs/iot-gateway/roadmap.md
- docs/iot-gateway/what-is-iot-gateway.md
Some improvements into ThingsBoard IoT Gateway documentation
> Adding information about CAN connector. 

- docs/user-guide/bulk-provisioning.md
'label' added to number of reserved parameters
> added: number of reserved parameters and their names

- docs/user-guide/resources/create-relation.sh
https://thingsboard.io/docs/user-guide/entities-and-relations/
> create-relation.sh fixed in the linked mentioned

- docs/reference.md
Correcting typos: "ThingsBard" to "ThingsBoard"
> Correcting typos: ThingsBard to ThingsBoard

- _data/docs-home.yml
- _includes/templates/iot-gateway/request-converter-custom-config.md
- _includes/templates/iot-gateway/request-converter-json-config.md
- _includes/templates/iot-gateway/rest-connector-anonymous-security-config.md
- _includes/templates/iot-gateway/rest-connector-basic-security-config.md
- _includes/templates/iot-gateway/rest-converter-custom-config.md
- _includes/templates/iot-gateway/rest-converter-json-config.md
- docs/iot-gateway/config/can.md
- docs/iot-gateway/config/odbc.md
- docs/iot-gateway/config/request.md
- docs/iot-gateway/config/rest.md
- docs/iot-gateway/what-is-iot-gateway.md
[IoT gateway] ODBC Connector improvements
[IoT gateway] CAN Connector improvements
> [IoT gateway] REST Connector documentation

- docs/user-guide/install/pe/cluster/docker-compose-setup.md
https://thingsboard.io/docs/user-guide/install/pe/cluster/docker-compose-setup/
> Fixed 'Configure DB' part for PE docker-compose-setup.md

- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- pricing/index.md
fix Trendz docker instructions
> fix Trendz docker install instruction

- docs/user-guide/install/pe/docker-windows.md
https://thingsboard.io/docs/user-guide/install/pe/docker-windows/
> Step numbering error on Installing TB PE using Docker ( Windows ) doc

- docs/trendz/visualizations-bar.md
- docs/trendz/visualizations-card.md
- docs/trendz/visualizations-heatmap.md
- docs/trendz/visualizations-line.md
- docs/trendz/visualizations-overview.md
- docs/trendz/visualizations-scatter.md
- docs/trendz/visualizations-tables.md
- pricing/index.md
add trendz training videos/update trendz pricing policy
> add trendz training videos

- docs/user-guide/contribution/how-to-contribute.md
looks like there is change from npm to yarn
> change profile npm-start to yarn-start

- _includes/templates/install/install-queue-docker-compose.md
- _includes/templates/install/pe-docker-queue-aws-sqs.md
- _includes/templates/install/pe-docker-queue-confluent-cloud.md
- _includes/templates/install/pe-docker-queue-in-memory.md
- _includes/templates/install/pe-docker-queue-kafka.md
- _includes/templates/install/pe-docker-queue-pub-sub.md
- _includes/templates/install/pe-docker-queue-rabbitmq.md
- _includes/templates/install/pe-docker-queue-service-bus.md
- docs/user-guide/install/cluster/docker-compose-setup.md
- docs/user-guide/install/pe/cluster/docker-compose-setup.md
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/upgrade-instructions.md
Changes are tested on local machine with VirtualBox with Ubuntu 20.04.
> Edited "docker-compose.yml" for Docker standalone instructions; fixed some upgrade instructions and cluster instructions

- products/paas/privacy-policy.md
- products/paas/terms-of-use.md
+ Terms of Use
+ Privasy Policy documents
> Added PaaS ToS and PP

- _careers/middle-devops.md
- Added "Middle DevOps engineer" vacancy
> Careers update 17.12.20

- products/paas/domains.md
Troubleshooting block for CNAME check is added
> CNAME Troubleshooting

- _includes/integrators.json
- _includes/rgn.json
- Removed "Teldio Corp."
- Added country "Russia"
- "Czechia" changed to "Czech Republic"
> Distributors Update

- _includes/templates/install/ubuntu-queue-kafka.md
- docs/samples/sample/sample.md
- docs/user-guide/contribution/how-to-contribute-your-device-integration-guide.md
Installation instruction correction (Kafka version changed)
guide corrections
> docs update

- _includes/integrators.json
> Added distributors

- docs/trendz/embed-visuals.md
- pricing/index.md
update Trendz trial code
fix JWT token param for trendz
> update Trendz trial code

- docs/user-guide/install/pe/cluster/docker-compose-setup.md
> docker compose hotfix

- docs/pe/user-guide/ota-updates.md
> OTA update

- _includes/docs/user-guide/contribution/widgets-development.md
> Updated examples in Widgets Development Guide (3.x)

- docs/contact-us.sass
- partners/hardware/apply/index.md
- partners/hardware/apply/thanks.md
- products/thingsboard-pe/install-pe.sass
- products/thingsboard-pe/install-thanks.md
- products/thingsboard-pe/install.md
- products/thingsboard-pe/install/aws.md
Pages:
- https://thingsboard.io/partners/hardware/apply/?program=silver
- https://thingsboard.io/partners/hardware/apply/thanks/
- https://thingsboard.io/products/thingsboard-pe/install/aws/?instance=maker
- https://thingsboard.io/products/thingsboard-pe/install-thanks/?instance=maker
> Redesign "Hardware Partner Program Apply"

- pricing/index.md
- products/paas/subscription.md
Added text "(except own SMTP server)"
- https://thingsboard.io/pricing/
- https://thingsboard.io/products/paas/subscription/
> Text changes

- docs/contact-us.md
- docs/contact-us.sass
- home.sass
- index.html
- https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/
The background ID matched from the ID of one of the titles
> ID of Background

- industries/index.md
- industries/industries.sass
- https://thingsboard.io/industries/
> Redesign "Industries" page

- css/styles.sass
- products/index.md
- products/products.sass
- https://thingsboard.io/products/
> Redesign "Products" page

- _sass/_base.sass
- https://thingsboard.io/docs/search/?q=Technical%20Support%20Team%20Lead
> Redesign "Search" page

- _includes/partner-script.js
- _includes/partner-style.css
- _includes/partners.json
- careers/careers.sass
- images/checked-box-icon.svg
- partners/hardware/index.html
- Added filter
- Edited mobile spacing
- Edited design
> ThingsBoard Hardware Partners

- _includes/docs/reference/coap-api.md
- _includes/docs/reference/http-api.md
- _includes/docs/reference/mqtt-api.md
- _includes/templates/api/json.md
JSON support for telemetry and attributes
> JSON support

- _includes/docs/pe/user-guide/self-registration.md
- _includes/docs/pe/user-guide/white-labeling.md
- docs/paas/user-guide/self-registration.md
- docs/paas/user-guide/white-labeling.md
self-registration and white-labeling for cloud fixed
> sys admin permissions for cloud fixed

- _sass/_base.sass
- https://thingsboard.io/docs/
> Added background for menu of documentation

- products/thingsboard-edge/index.md
- https://thingsboard.io/products/thingsboard-edge/
> Edge (Removed customers)

- docs/reference/releases.md
> ThingsBoard 3.3 Release

- _includes/templates/solution-templates.md
- https://thingsboard.io/docs/pe/solution-templates/overview/
> Solution templates (version 3.3. to version 3.3.1.)

- _includes/integrators.json
- Hinditron Corp. Systems Pvt. Ltd
> Added new distributor

- _includes/docs/user-guide/install/config.md
https://github.com/thingsboard/thingsboard/releases/tag/v3.3
https://github.com/thingsboard/thingsboard/blob/v3.3/application/src/main/resources/thingsboard.yml#L605
> add config docs for MQTT/MQTTS simultaneously on Thingsboard 3.3

- products/products.sass
-https://thingsboard.io/products/
> Updated hover effect on TB Edge

- _includes/docwithnav.html
- _sass/_base.sass
- https://thingsboard.io/docs/paas/user-guide/attributes/
> Copy Code Button

- _includes/partners.json
- Removed duplicate "Things On Edge"
- https://thingsboard.io/partners/hardware/
> Removed duplicate

- docs/user-guide/install/gcp.md
- docs/user-guide/install/installation-options.sass
- docs/user-guide/install/pe/gcp.md
- Added text
- https://thingsboard.io/docs/user-guide/install/gcp/
> Added text on page "gcp"

- _includes/integrators.json
- https://thingsboard.io/partners/distributors/
- data.it-novum.com
- mail@technopyne.lt
> Updated links

- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.8.0/trendz-centos-download.sh
- docs/trendz/install/resources/1.8.0/trendz-centos-installation.sh
- docs/trendz/install/resources/1.8.0/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.8.0/trendz-ubuntu-installation.sh
- docs/trendz/install/rhel.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/install/ubuntu.md
- docs/trendz/install/windows.md
- docs/trendz/releases.md
- pricing/index.md
Change Trendz trial coupon on site
Instructions for Trenz upgrade to the latestversion
> Trendz upgrade to 1.8.2

- _includes/docs/user-guide/rule-engine-2-0/ce-enrichment-nodes.md
add a description for feature, which added in this PR:
https://github.com/thingsboard/thingsboard/pull/5550
> [3.3.3] Add a description for a new feature in customer attribute, tenant attribute, and related attribute rule node

- README.md
- generate-previews.sh
Preview generator documented. Generate-preview script usability improved
> [3.3.3] Preview generator documented. Generate-preview script usability improved

- _includes/docs/user-guide/rule-engine-2-0/ce-action-nodes.md
Related to https://github.com/thingsboard/thingsboard/pull/5821
> [3.3.3] add details about ignoreMetadataTs for 'Save Timeseries Node'

- _careers/techops-engineer.md
- https://thingsboard.io/careers/techops-engineer/
> Careers update

- pricing/index.md
Use the following command to check the broken links. Don't forget to substitute YOUR_IP with the internal IP address of your machine. 
```bash
docker run linkchecker/linkchecker http://YOUR_IP:4000/
```
> Set max number of devices and assets to 1000 for perpertual subscription

- _data/reference.yml
- _includes/docs/reference/performance-comparison.md
- _includes/docs/reference/performance/performance-test-methodology.md
- _includes/docs/reference/performance/setup-aws-instances.md
- docs/reference/performance/setup-aws-instances.md
Use the following command to check the broken links. Don't forget to substitute YOUR_IP with the internal IP address of your machine. 
```bash
docker run linkchecker/linkchecker http://YOUR_IP:4000/
```
> performance articles refactored regarding review

- _includes/docs/reference/performance-aws-instances.md
performance tests fixed missing tag </details>
```bash
```
> performance tests fixed missing tag </details>

- _config.yml
- docs/pe/reference/releases.md
- docs/reference/releases.md
- docs/user-guide/install/pe/resources/3.3.4pe/thingsboard-centos-download.sh
- docs/user-guide/install/pe/resources/3.3.4pe/thingsboard-centos-installation.sh
- docs/user-guide/install/pe/resources/3.3.4pe/thingsboard-ubuntu-download.sh
- docs/user-guide/install/pe/resources/3.3.4pe/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/pe/windows.md
- docs/user-guide/install/resources/3.3.4/thingsboard-centos-download.sh
- docs/user-guide/install/resources/3.3.4/thingsboard-centos-installation.sh
- docs/user-guide/install/resources/3.3.4/thingsboard-ubuntu-download.sh
- docs/user-guide/install/resources/3.3.4/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/upgrade-instructions.md
> Release 3.3.4

- _includes/docs/edge/index.md
- docs/edge/index.md
- docs/pe/edge/index.md
> Fixed edge index page - navigate to correct version

- pricing/index.md
> Updated edge trial coupon. Typo fix

- _config.yml
- _data/edge/installation.yml
- docs/edge/releases.md
- docs/pe/edge/releases.md
- docs/user-guide/install/edge/resources/3.3.4.1/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/3.3.4.1/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/3.3.4.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/3.3.4.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/resources/3.3.4.1/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/3.3.4.1/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/3.3.4.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/3.3.4.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Edge 3.3.4.1 release

- cookie-policy/index.md
> Fixed Typo and added Dismiss adjustment

- pricing/index.md
Effective starting 18th of July, 2022
```bash
```
> Perpetual license price update

- _includes/docs/user-guide/install/config.md
Fix configuration page
https://thingsboard.io/docs/pe/user-guide/install/config/
> fix-configuration-page

- _includes/docs/pe/reference/python-rest-client.md
- _includes/docs/reference/python-rest-client.md
> Added description for version control feature examples in Python REST client

- _config.yml
- docs/pe/reference/releases.md
- docs/reference/releases.md
- docs/user-guide/install/pe/resources/3.4.1pe/thingsboard-centos-download.sh
- docs/user-guide/install/pe/resources/3.4.1pe/thingsboard-centos-installation.sh
- docs/user-guide/install/pe/resources/3.4.1pe/thingsboard-ubuntu-download.sh
- docs/user-guide/install/pe/resources/3.4.1pe/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/resources/3.4.1/thingsboard-centos-download.sh
- docs/user-guide/install/resources/3.4.1/thingsboard-centos-installation.sh
- docs/user-guide/install/resources/3.4.1/thingsboard-ubuntu-download.sh
- docs/user-guide/install/resources/3.4.1/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/upgrade-instructions.md
> Release 3.4.1

- _config.yml
- docs/edge/releases.md
- docs/pe/edge/releases.md
- docs/user-guide/install/edge/resources/3.4.1/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/3.4.1/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/3.4.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/3.4.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/resources/3.4.1/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/3.4.1/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/3.4.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/3.4.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Edge 3.4.1 Release

- _includes/docs/user-guide/install/mqtt-transport.md
- _includes/docs/user-guide/ssl/mqtt-over-ssl.md
sync doc with [PR: Update the MQTT SSL key store type example configuration file #7078
](https://github.com/thingsboard/thingsboard/pull/7078)
```bash
```
> MQTT transport SSL configuration document

- css/styles.sass
- google-iot-core-alternative/google-iot-core-alternative.sass
- google-iot-core-alternative/index.md
> Google IoT Core alternative

- pricing/index.md
> Add new perpetual item in PE pricing

- _data/gw/docs-home.yml
- _includes/templates/iot-gateway/mqtt-converter-bytes-config.md
- _includes/templates/iot-gateway/mqtt-converter-json-config.md
- _includes/templates/iot-gateway/ocpp-connector-anonymous-security-config.md
- _includes/templates/iot-gateway/ocpp-connector-basic-security-config.md
- _includes/templates/iot-gateway/ocpp-connector-insecure-connection-config.md
- _includes/templates/iot-gateway/ocpp-connector-tls-connection-config.md
- _includes/templates/iot-gateway/ocpp-connector-token-security-config.md
- _includes/templates/iot-gateway/security-tls-config.md
- _includes/templates/iot-gateway/security-usernamepassword-config.md
- docs/iot-gateway/config/modbus.md
- docs/iot-gateway/config/mqtt.md
- docs/iot-gateway/config/ocpp.md
- docs/iot-gateway/config/opc-ua.md
- docs/iot-gateway/config/rest.md
- docs/iot-gateway/config/socket.md
- docs/iot-gateway/config/xmpp.md
- docs/iot-gateway/configuration.md
- docs/iot-gateway/getting-started.md
- docs/iot-gateway/guides/how-to-use-get-set-rpc-methods.md
- docs/iot-gateway/install/docker-installation.md
- docs/iot-gateway/install/docker-windows.md
- docs/iot-gateway/install/source-installation.md
- docs/iot-gateway/installation.md
- docs/iot-gateway/what-is-iot-gateway.md
> Updated Gateway docs v.3.2

- _careers/application-support-engineer.md
- _careers/middle-frontend-developer.md
- _careers/middle-java-developer.md
- _careers/techops-engineer.md
> in the careers section, changed 10,000+ stars to 12,000+ stars

- docs/user-guide/install/upgrade-instructions.md
> Stop ThingsBoard service before service upgrade

- _includes/docs/user-guide/rule-engine-2-0/ce-action-nodes.md
> Updated description of GPS geofencing events rule node

- _includes/cookie-consent.html
```bash
```
**Before:** 
**After:**
> Change of cookie policy notification style in mobile mode

- docs/paas/user-guide/integrations/kafka.md
Fixed file with paths of pics for kafka guide paas
```bash
```
> Fixed file with paths of pics for kafka guide paas

- docs/trendz/calculated-fields.md
- docs/trendz/connect-thingsboard.md
- docs/trendz/embed-visuals.md
- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.9.2/trendz-centos-download.sh
- docs/trendz/install/resources/1.9.2/trendz-centos-installation.sh
- docs/trendz/install/resources/1.9.2/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.9.2/trendz-ubuntu-installation.sh
- docs/trendz/install/rhel.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/install/ubuntu.md
- docs/trendz/install/windows.md
- docs/trendz/releases.md
> Trendz upgrade from 1.8.2 to 1.9.2

- _data/gw/installation.yml
> Fixed installation menu links

- docs/user-guide/install/upgrade-instructions.md
Is there a template? Because the last three versions don't have this change.
```bash
```
> Stop service before upgrade

- _config.yml
- docs/pe/reference/releases.md
- docs/reference/releases.md
- docs/user-guide/install/pe/resources/3.4.3pe/thingsboard-centos-download.sh
- docs/user-guide/install/pe/resources/3.4.3pe/thingsboard-centos-installation.sh
- docs/user-guide/install/pe/resources/3.4.3pe/thingsboard-ubuntu-download.sh
- docs/user-guide/install/pe/resources/3.4.3pe/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/resources/3.4.3/thingsboard-centos-download.sh
- docs/user-guide/install/resources/3.4.3/thingsboard-centos-installation.sh
- docs/user-guide/install/resources/3.4.3/thingsboard-ubuntu-download.sh
- docs/user-guide/install/resources/3.4.3/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/upgrade-instructions.md
> Release 3.4.3

- pricing/index.md
> Update pricing page

- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.9.2/trendz-centos-download.sh
- docs/trendz/install/resources/1.9.2/trendz-centos-installation.sh
- docs/trendz/install/resources/1.9.2/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.9.2/trendz-ubuntu-installation.sh
- docs/trendz/install/rhel.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/install/ubuntu.md
- docs/trendz/install/windows.md
- docs/trendz/releases.md
> Trendz upgrade from 1.9.2 to 1.9.2 hot fix 1

- _includes/docs/pe/user-guide/integrations/opc-ua.md
- docs/pe/edge/user-guide/integrations/opc-ua.md
> Added details on OPC UA device node pattern regular expression mapping

- _layouts/thingsboard-edge.html
- products/thingsboard-edge/index.md
> Edge product page - replace pricing page with getting started guide

- _includes/integrators.json
> IoT Experts card  adjustment

- _layouts/pricing.html
- _layouts/trendz.html
- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.9.2/trendz-centos-download.sh
- docs/trendz/install/resources/1.9.2/trendz-centos-installation.sh
- docs/trendz/install/resources/1.9.2/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.9.2/trendz-ubuntu-installation.sh
- docs/trendz/install/rhel.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/install/ubuntu.md
- docs/trendz/install/windows.md
- docs/trendz/releases.md
- pricing/index.md
- pricing/pricing.sass
- products/trendz/index.md
> Add Trendz cloud pricing details

- _includes/templates/install/docker-install.md
- docs/user-guide/install/cluster/docker-compose-setup.md
- docs/user-guide/install/docker.md
- docs/user-guide/install/pe/cluster/docker-compose-setup.md
- docs/user-guide/install/pe/docker.md
> Change docker instructions for docker engine install

- _includes/templates/edge/bind-port-changed-banner.md
- _includes/templates/edge/install/compatibility-warning-general.md
- _includes/templates/edge/install/compatibility-warning-version.md
- _includes/templates/edge/install/docker_compose_details_explain.md
- _includes/templates/edge/install/open-edge-ui.md
- _includes/templates/edge/install/ubuntu-configure-edge.md
- _includes/templates/edge/install/windows-configure-edge.md
- _includes/templates/install/docker/docker-compose-standalone-banner.md
- _includes/templates/install/docker/docker-compose-up.md
- _includes/templates/install/docker/docker-create-folders-sudo-explained.md
- docs/user-guide/install/edge/deb-installation.md
- docs/user-guide/install/edge/docker-windows.md
- docs/user-guide/install/edge/docker.md
- docs/user-guide/install/edge/rhel.md
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/edge/windows.md
- docs/user-guide/install/pe/edge/deb-installation.md
- docs/user-guide/install/pe/edge/docker-windows.md
- docs/user-guide/install/pe/edge/docker.md
- docs/user-guide/install/pe/edge/rhel.md
- docs/user-guide/install/pe/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/windows.md
> Edge/Server compatibility versions rules. Docker install guide updates.

- docs/user-guide/install/upgrade-instructions.md
> [WIP][3.5] Added note for 3.5PE upgrade instruction

- _includes/head-header.html
> Header navigation menu behaviour enhancement

- pricing/index.md
> FAQ update

- README.md
> Added deployment of the site in docker

- _includes/integrators.json
> added Fourier to ThingsBoard Distributors page

- _includes/docs/devices-library/blocks/basic/thingsboard-upload-example-dashboard.md
- _includes/docs/devices-library/blocks/microcontrollers/esp32-arduino-library-install-block.md
- _includes/docs/devices-library/blocks/microcontrollers/general-code-to-program-block.md
- docs/devices-library/resources/dashboards/microcontrollers/basic/dashboard.json
- docs/devices-library/resources/dashboards/microcontrollers/camera/dashboard.json
- docs/devices-library/resources/dashboards/microcontrollers/rgb-led/dashboard.json
> Fixes for devices library article

- _includes/docs/devices-library/blocks/single-board-computers/update-shared-attributes-block.md
- _includes/docs/devices-library/blocks/single-board-computers/using-rpc-block.md
- _includes/templates/device-library/minicomputers/device-imported-dashboard.md
> Updated shared attrs and RPC section

- _includes/docs/getting-started-guides/connectivity.md
- _includes/docs/pe/index.md
- docs/index.md
> Added links from index page and connectivity guide to Devices library

- pricing/index.md
> Grammatical error. Removed the extra word "for" on the Subscription plans page

- docs/edge/roadmap.md
- docs/pe/edge/roadmap.md
> Removed edge 3.5 roadmap

- _includes/integrators.json
> add new distributors - Wiifor

- pricing/index.md
- products/paas/subscription.md
> Changes in Subscription plans

- _includes/templates/install/tb-350-update.md
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/upgrade-instructions.md
> Add note for upgrade to 3.5 that Angular version was changed

- _includes/integrators.json
> Added Jems Group to a partners list

- _includes/docs/reference/coap-api.md
- docs/pe/reference/resources/coap-telemetry.sh
> CoAP Device API Reference. Minor fixed text

- _includes/docs/reference/http-api.md
> HTTP Device API Reference. Edited commands

- _includes/templates/install/tb-350-update.md
> Make v3.5.0 upgrade note (about Angular) banner more cautionary

- _config.yml
- docs/edge/releases.md
- docs/pe/edge/releases.md
- docs/reference/releases.md
- docs/user-guide/install/edge/resources/3.5/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/3.5/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/3.5/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/3.5/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/resources/3.5/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/3.5/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/3.5/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/3.5/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Edge 3.5 release - release notes, install and upgrade instruction update

- _includes/integrators.json
> New distributor has been added to the distributors page (Epithos Co., Ltd)

- _careers/middle-ui-ux-designer.md
> Careers page. Fixed grammatical error in text

- _config.yml
- _data/mobile-pe/docs-home.yml
- _data/mobile/docs-home.yml
- _includes/docs/mobile/getting-started.md
- _includes/docs/pe/reference/dart-client.md
- docs/paas/reference/dart-client.md
- docs/pe/reference/releases.md
- docs/reference/dart-client.md
- docs/reference/releases.md
- docs/reference/roadmap.md
- docs/user-guide/install/pe/resources/3.5.1pe/thingsboard-centos-download.sh
- docs/user-guide/install/pe/resources/3.5.1pe/thingsboard-centos-installation.sh
- docs/user-guide/install/pe/resources/3.5.1pe/thingsboard-ubuntu-download.sh
- docs/user-guide/install/pe/resources/3.5.1pe/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/resources/3.5.1/thingsboard-centos-download.sh
- docs/user-guide/install/resources/3.5.1/thingsboard-centos-installation.sh
- docs/user-guide/install/resources/3.5.1/thingsboard-ubuntu-download.sh
- docs/user-guide/install/resources/3.5.1/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/upgrade-instructions.md
> Release 3.5.1

- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/upgrade-instructions.md
> Upgrade instructions. Added the "copy-paste" function to the commands

- _includes/partners.json
> The title has been edited

- _includes/docs/user-guide/ui/tenants-pe.md
- _includes/docs/user-guide/ui/tenants.md
- docs/pe/user-guide/ui/tenants.md
- docs/user-guide/ui/tenants.md
> minor edits in "Tenant" documentation (PAAS)

- _includes/templates/helloworld-pe/coap.md
- _includes/templates/helloworld-pe/http.md
- _includes/templates/helloworld-pe/mqtt-linux.md
- _includes/templates/helloworld/coap.md
- _includes/templates/helloworld/http.md
- _includes/templates/helloworld/mqtt-linux.md
- docs/getting-started-guides/helloworld-pe.md
> Getting Started giude. Minor fix command

- _layouts/thingsboard-edge.html
> Fixed click on request-demo button on edge product page

- _includes/head-header.html
> Fixed display of the main menu

- _config.yml
- docs/edge/releases.md
- docs/pe/edge/releases.md
- docs/user-guide/install/edge/resources/3.5.1.1/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/3.5.1.1/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/3.5.1.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/3.5.1.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/resources/3.5.1.1/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/3.5.1.1/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/3.5.1.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/3.5.1.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Edge 3.5.1.1 hotfix release

- _includes/docs/devices-library/blocks/microcontrollers/camera-code-to-program-block.md
- docs/devices-library/orange-pi-4.md
- docs/paas/devices-library/orange-pi-4.md
- docs/pe/devices-library/orange-pi-4.md
> Fix for devices library camera guides

- support-ukraine/index.md
> removed the one line

- _includes/integrators.json
> Add a new distributor - Clavis IT

- _includes/templates/coap-dtls/coap-client-dtls.md
- docs/iot-gateway/install/source-installation.md
- docs/user-guide/install/building-from-source.md
- docs/user-guide/install/cluster/docker-compose-setup.md
- docs/user-guide/install/cluster/minikube-cluster-setup.md
- docs/user-guide/install/cluster/openshift-cluster-setup.md
- docs/user-guide/install/pe/cluster/aws-microservices-setup.md
- docs/user-guide/install/pe/cluster/aws-monolith-setup.md
- docs/user-guide/install/pe/cluster/azure-microservices-setup.md
- docs/user-guide/install/pe/cluster/azure-monolith-setup.md
- docs/user-guide/install/pe/cluster/docker-compose-setup.md
- docs/user-guide/install/pe/cluster/gcp-microservices-setup.md
- docs/user-guide/install/pe/cluster/gcp-monolith-setup.md
- docs/user-guide/install/pe/cluster/minikube-cluster-setup.md
> Added "--depth 1" parameter to "git clone..." commands

- _includes/docs/user-guide/tbel.md
```bash
var input = '{\"hello\": \"world\"}'
return decodeToJson(input); // Returns '{"hello": "world"}'
```
> [3.5.2]tbel_decodeToJson_with_Parameter_String_value

- _includes/docs/user-guide/tbel.md
Reverts thingsboard/thingsboard.github.io#1136
> Revert "[3.5.2]tbel_decodeToJson_with_Parameter_String_value"

- docs/user-guide/resources/firmware/http_firmware_client.py
Added missing import for example client.
```bash
```
> Firmware OTA guide

- _includes/integrators.json
> Add new distributor - qnectd

- _includes/content-toggle.liquid
**BEFORE**:
**AFTER**:
```bash
```
> Fixed table of content showing all headings when toggle is used on page

- _includes/integrators.json
- _includes/rgn.json
> Added two new distributors. And added new country filters - Spain and Portugal

- _includes/integrators.json
> Changed the contact details for IoT Experts integrator

- docs/user-guide/contribution/how-to-contribute.md
> Correct typo in documentation

- _includes/templates/integration/aws-iot/aws-iot-downlink-converter-config-javascript.md
- _includes/templates/integration/aws-iot/aws-iot-downlink-converter-config-tbel.md
> AWS IoT Integration. Minor fixed downlink converter

- _includes/head-header.html
- _includes/images-gallery.html
- _includes/images-gallery.liquid
- _includes/images-gallery.sass
- _layouts/plain.html
> Fixed image gallery: image opening in browser tab instead of gallery

- _data/trendz/docs-home.yml
- docs/trendz/install/cloud.md
- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.10.3/trendz-centos-download.sh
- docs/trendz/install/resources/1.10.3/trendz-centos-installation.sh
- docs/trendz/install/resources/1.10.3/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.10.3/trendz-ubuntu-installation.sh
- docs/trendz/install/rhel.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/install/ubuntu.md
- docs/trendz/install/windows.md
- docs/trendz/mix-sql-datasource.md
- docs/trendz/releases.md
> Trendz 1.10.3 release

- fleet-tracking.md
- index.html
- smart-energy.md
> update tags for home, fleet tracking and smart energy pages

- _includes/docs/devices-library/blocks/integrations/converters/custom-decoding/ws101-smart-button.js
- _includes/docs/devices-library/blocks/integrations/converters/custom-decoding/ws202-pir-and-light-sensor.js
- _includes/docs/devices-library/blocks/microcontrollers/camera-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/general-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/oled-example-code-to-program-block.md
Contains changes only in the code blocks.
```bash
```
> Changes for thingsboard client sdk v12 release (Cpp)

- docs/devices-library/beaglebone-black.md
- docs/devices-library/raspberry-pi-3-model-B-plus.md
- docs/devices-library/raspberry-pi-4.md
- docs/devices-library/raspberry-pi-pico-w.md
- docs/devices-library/upesy-esp32-wroom-devkit.md
- docs/paas/devices-library/raspberry-pi-3-model-B-plus.md
- docs/paas/devices-library/raspberry-pi-4.md
- docs/paas/devices-library/raspberry-pi-pico-w.md
- docs/paas/devices-library/ug65-lorawan-gateway.md
- docs/paas/devices-library/ug67-lorawan-gateway.md
- docs/pe/devices-library/raspberry-pi-3-model-B-plus.md
- docs/pe/devices-library/raspberry-pi-4.md
- docs/pe/devices-library/raspberry-pi-pico-w.md
> Minor fixes, like not shown TOC on some devices, vendor name, etc

- _includes/docs/user-guide/ui/microsoft-teams-settings.md
> fixing link to the notification doc

- google-iot-core-alternative/index.md
> Minor changes to GCP IoT Core article

- js/script.js
> Improved image gallery: disabled loop image when using keyboard arrow

- _includes/docs/devices-library/blocks/basic/thingsboard-create-device-block.md
> minor fixed text in the "How to connect Arduino Nano RP2040 Connect to ThingsBoard?" documentation

- index.html
> Added JS code to hide heavy elements of the mobile version

- _includes/images-gallery.html
- _includes/images-gallery.liquid
Removed asterisks and extra quotes in images alt parameter, in images-gallery files
```bash
```
> Removed extra quotes and fixed alt for images

- _includes/head-header.html
- _sass/_base.sass
- docs/samples/nettrartu-x/tutorial.md
> Replaced main menu a link element with span and removed empty links

- home.sass
- index.html
- iot-use-cases.md
> Changed links with not descriptive text

- _data/docs-home.yml
- _data/paas/docs-home.yml
- _data/pe/docs-home.yml
- _includes/docs/user-guide/templatization.md
- docs/paas/user-guide/templatization.md
- docs/pe/user-guide/templatization.md
- docs/user-guide/templatization.md
> Add documentation about templatization feature

- index.html
> Big pictures were made lazy

- _layouts/thingsboard-paas.html
- _layouts/thingsboard-pe.html
- home.sass
- index.html
- products/paas/thingsboard-paas.sass
- products/thingsboard-edge/thingsboard-edge.sass
- products/thingsboard-pe/thingsboard-pe.sass
> Added width checking

- README.md
- generate_config_pages.py
- release.sh
Updated release.sh to use command line arguments for TB type and  TB  repository path
```bash
```
> Updated release.sh 

- _layouts/thingsboard-paas.html
- _layouts/thingsboard-pe.html
- index.html
> Added alternative for cover video for PE and Cloud pages

- index.html
> Added new version of big content hidding

- _layouts/thingsboard-paas.html
- _layouts/thingsboard-pe.html
> Removed the header video loading on mobile for PE and Cloud pages

- products/paas/subscription.md
> ThingsBoard Cloud Subscription plans definition page. Edited API Limits for Data point storage days

- robots.txt
> Changed the robots.txt file

- _sass/_base.sass
> Fixed align items of submenu items

- _config.yml
- docs/pe/reference/releases.md
- docs/reference/releases.md
- docs/reference/roadmap.md
- docs/user-guide/install/pe/resources/3.6.1pe/thingsboard-centos-download.sh
- docs/user-guide/install/pe/resources/3.6.1pe/thingsboard-centos-installation.sh
- docs/user-guide/install/pe/resources/3.6.1pe/thingsboard-ubuntu-download.sh
- docs/user-guide/install/pe/resources/3.6.1pe/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/resources/3.6.1/thingsboard-centos-download.sh
- docs/user-guide/install/resources/3.6.1/thingsboard-centos-installation.sh
- docs/user-guide/install/resources/3.6.1/thingsboard-ubuntu-download.sh
- docs/user-guide/install/resources/3.6.1/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/upgrade-instructions.md
> Release 3.6.1

- _includes/head-header.html
- _layouts/thingsboard-pe.html
- _layouts/use-case.html
- home.sass
- index.html
- products/thingsboard-pe/index.md
- products/thingsboard-pe/thingsboard-pe.sass
> Fixed html issue for head-header in accordance with the w3 recommendations

- _includes/docs/user-guide/tbel.md
> Added parseLong to TBEL doc

- _includes/integrators.json
> Added new distributor - McRegem Srl

- products/thingsboard-pe/index.md
- products/thingsboard-pe/thingsboard-pe.sass
- robots.txt
> Changed robots.txt

- _includes/docs/user-guide/tbel.md
> [fix_bug][3.6.1]tbel: tbDate_pattern_Corrected_grammatical

- _includes/templates/edge/install/windows-db-postgresql.md
- _includes/templates/install/postgres-install-ubuntu.md
- _includes/templates/install/windows-db-hybrid-timescale.md
- _includes/templates/install/windows-db-hybrid.md
- _includes/templates/install/windows-db-postgresql.md
- docs/trendz/install/windows.md
> Installing ThingsBoard on Ubuntu and Windows doc. Changed PostgreSQL version from 12 to 15

- use-cases/use-cases.sass
Add box-shadow to use-case pages
```bash
```
> Add box-shadow to use-case pages

- products/paas/terms-of-use.md
> Added the target attribute to the sanction list link

- _includes/images-gallery.html
- _includes/images-gallery.liquid
The documentation updated for image showing fix.
```bash
```
> Changed scripts for image-gallery parsing

- _includes/docs/user-guide/tbel.md
> TBEL: refactoring parts: Using Java Classes, tbDate

- _includes/docs/reference/msa.md
- docs/samples/ble/raspberry-esp32-xiaomi-sensor-htu21d.md
- products/paas/domains.md
fixed external broken links
```bash
```
> fixed external broken links

- _includes/docs/devices-library/blocks/microcontrollers/thingsboard-arduino-library-install-block.md
- _includes/docs/devices-library/blocks/single-board-computers/general-code-to-program-block.md
- _includes/docs/devices-library/guides/m5stack-timer-camera-f.md
- _includes/docs/devices-library/guides/m5stack-timer-camera-x.md
The documentation updated for guides in devices library.
```bash
```
> Fix for typo and updated board naming

- _config.yml
- _includes/docs/mqtt-broker/install/aws-cluster-setup.md
- _includes/docs/mqtt-broker/install/config.md
- _includes/templates/mqtt-broker/install/aws/eks-prerequisites.md
- _includes/templates/mqtt-broker/install/migration.md
- _includes/templates/mqtt-broker/install/upgrade-hint.md
- _includes/templates/mqtt-broker/install/windows/windows-install.md
- docs/mqtt-broker/install/cluster/azure-cluster-setup.md
- docs/mqtt-broker/install/cluster/docker-compose-setup.md
- docs/mqtt-broker/install/cluster/minikube-cluster-setup.md
- docs/mqtt-broker/install/docker-windows.md
- docs/mqtt-broker/install/docker.md
- docs/mqtt-broker/install/resources/1.2.1/tbmq-cluster-mode-pull.sh
- docs/mqtt-broker/install/resources/1.2.1/tbmq-single-node-pull.sh
- docs/mqtt-broker/install/upgrade-instructions.md
- docs/mqtt-broker/releases.md
The documentation updated for tbmq new release.
```bash
```
> TBMQ - release 1.2.1

- _includes/docs/reference/mqtt-api.md
- _includes/templates/helloworld-pe/mqtt-linux.md
- _includes/templates/helloworld-pe/mqtt-windows.md
- _includes/templates/helloworld/mqtt-linux.md
- _includes/templates/helloworld/mqtt-windows.md
> Setup mosquitto_pub guide. For Windows and Linux

- _data/docs-home.yml
- _data/paas/docs-home.yml
- _data/pe/docs-home.yml
- docs/samples/sodaq/sodaq.md
- docs/user-guide/rule-engine-2-0/tutorials/check-relation-tutorial.md
- docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms-with-details.md
- docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms.md
- docs/user-guide/rule-engine-2-0/tutorials/send-email-to-customer.md
- docs/user-guide/rule-engine-2-0/tutorials/send-email.md
- products/paas/domains.md
> Edited links to the rule chain nodes. And added "Data processing & actions" navigation menu

- _includes/templates/edge/create-tb-db-rhel.md
- _includes/templates/install/create-tb-db-rhel.md
- _includes/templates/install/gcp/provision-postgresql.md
- _includes/templates/install/pe-docker-queue-aws-sqs.md
- _includes/templates/install/pe-docker-queue-confluent-cloud.md
- _includes/templates/install/pe-docker-queue-in-memory.md
- _includes/templates/install/pe-docker-queue-kafka.md
- _includes/templates/install/pe-docker-queue-pub-sub.md
- _includes/templates/install/pe-docker-queue-rabbitmq.md
- _includes/templates/install/pe-docker-queue-service-bus.md
- _includes/templates/install/postgres-install-rhel.md
- _includes/templates/install/windows-pe-docker-queue-aws-sqs.md
- _includes/templates/install/windows-pe-docker-queue-confluent-cloud.md
- _includes/templates/install/windows-pe-docker-queue-in-memory.md
- _includes/templates/install/windows-pe-docker-queue-kafka.md
- _includes/templates/install/windows-pe-docker-queue-pub-sub.md
- _includes/templates/install/windows-pe-docker-queue-rabbitmq.md
- _includes/templates/install/windows-pe-docker-queue-service-bus.md
- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- docs/trendz/install/rhel.md
- docs/user-guide/install/edge/docker-windows.md
- docs/user-guide/install/edge/docker.md
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/docker-windows.md
- docs/user-guide/install/pe/edge/docker.md
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Changed PostgreSQL version from 12 to 15. Ubuntu, Docker, Red Hat, and Windows doc.

- _includes/docs/pe/user-guide/install/coap-transport-config.md
- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/ie-executor-config.md
- _includes/docs/pe/user-guide/install/lwm2m-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/pe/user-guide/install/snmp-transport-config.md
- _includes/docs/pe/user-guide/install/vc-executor-config.md
- _includes/docs/user-guide/install/coap-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/lwm2m-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/snmp-transport-config.md
- _includes/docs/user-guide/install/vc-executor-config.md
Updated config pages
```bash
```
> Updated config pages

- products/paas/subscription.md
Fixed values for such Rate Limits:
* All Transport messages (Device)
* Telemetry Transport messages (Device)
* Telemetry Transport data points (Device)
```bash
```
> Fix Rate Limit values

- _includes/templates/install/ubuntu-queue-kafka.md
- Added commands to start Zookeeper and Kafka on system boot
- Updated Kafka download link
```bash
```
> Updated instructions for Kafka installation on Ubuntu

- _includes/docs/user-guide/telemetry.md
- docs/paas/user-guide/resources/web-socket.html
- docs/pe/user-guide/resources/web-socket.html
- docs/user-guide/resources/telemetry-websocket-example.js
- docs/user-guide/resources/web-socket.html
> Update WebSocket API documentation

- _includes/rgn.json
The documentation updated for https://thingsboard.io/partners/distributors/
```bash
```
> Remove "Russia" from the distributors list

- _includes/docs/user-guide/ui/mail-settings.md
> Mail Settings. minor edited text (grammatical errors)

- docs/iot-gateway/config/odbc.md
The documentation updated for the Gateway ODBC Connector configuration guide.
```bash
```
> Corrected grammar for the Gateway ODBC Connector configuration guide

- docs/iot-gateway/config/bacnet.md
The documentation updated for the Gateway BACnet Connector configuration guide.
```bash
```
> Corrected grammar for the Gateway BACnet Connector configuration guide

- docs/iot-gateway/config/can.md
The documentation updated for Gateway CAN Connector configuration guide.
```bash
```
> Corrected grammar for the Gateway CAN Connector configuration guide

- _includes/integrators.json
- _includes/rgn.json
> Added new distributor - 3D Alem

- _includes/docs/pe/user-guide/integrations/tcp.md
> TCP Integration guide. Minor edited text

- docs/user-guide/install/pe/upgrade-instructions.md
- docs/user-guide/install/upgrade-instructions.md
Renamed "3.0.1-cassandra" to "cassandra-latest-to-postgres"  in accordance with changes in project
```bash
```
> Renamed "3.0.1-cassandra" to "cassandra-latest-to-postgres"

- _includes/head-header.html
- index.html
> Optimize for home page svg loading

- _includes/head-header.html
- _layouts/plain.html
Added properties for subdomains cookies.
```bash
```
> Fixed cookies properties

- _includes/head-header.html
- _layouts/plain.html
Reverts thingsboard/thingsboard.github.io#1344
> Revert "Fixed cookies properties"

- _includes/docs/devices-library/guides/iot-gateway-cell-1024.md
- docs/paas/devices-library/iot-gateway-cell-1024.md
> Fixed text for IoT Gateway Cell 1024 (paas) device

- products/paas/subscription.md
> ThingsBoard Cloud Subscription plans definition. Updated API Limits

- _includes/integrators.json
> edited email section for Fourier distributor

- _includes/docs/user-guide/telemetry.md
> Working with telemetry data page. Edited "Data retention" section.

- _includes/cookie-consent.html
- _includes/head-header.html
- index.html
Fixed CLS warning.
```bash
```
> Improve for CLS

- _includes/footer.html
- css/critical.css
Minus 8 requests for init loading.
```bash
```
> Optimize loading footer

- _includes/head-header.html
Hotfix width and height icon
```bash
```
> Hotfix width and height icon

- _includes/head-header.html
- css/critical.css
Fixed CLS warnings
```bash
```
> Fixed CLS warnings

- _includes/docs/edge/architecture.md
- _includes/templates/edge/use-cases/prerequisites.md
> Fixed broker link on edge architecture page

- _includes/head-header.html
Optimize loading for mobile
```bash
```
> Optimize loading

- _includes/docs/mobile/getting-started.md
- _includes/docs/mobile/release.md
- docs/mobile/scripts/firebase_initialization_script.dart
> Getting started with ThingsBoard Mobile Application guide. How to build and release mobile app

- _includes/docs/mobile/getting-started.md
- docs/mobile/scripts/firebase_initialization_script.dart
…ard Mobile Application
```bash
```
> Added "Configure notifications" step into Getting started with ThingsBoard PE Mobile Application

- _includes/integrators.json
> Added new distributor - Atea Sverige AB

- _includes/docs/devices-library/blocks/microcontrollers/esp32-arduino-library-install-block.md
- _includes/docs/devices-library/blocks/microcontrollers/m5stack-arduino-library-install-block.md
- _includes/docs/devices-library/blocks/microcontrollers/raspberry-pi-pico-arduino-library-install-block.md
> Devices Library. Added one screenshot to Raspberry Pi Pico, M5Stack Timer Camera F, add M5Stack Timer Camera X pages

- js/script.js
> Fixed incorrect initialization toc toggle set content

- _includes/head-header.html
- _scss/bs-cutted.scss
- css/bs-cutted.sass
- css/critical.css
> Added only needed styles from bootstrap file

- _scss/bs-cutted.scss
> Changed variables usage approach

- _includes/docs/user-guide/contribution/widgets-development.md
Fix wrong broadcast documentation. See https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/services/broadcast.models.ts#L27
> Update widgets-development.md: Fix wrong broadcast documentation

- _sass/_base.sass
- js/script.js
> Fixed the code blocks height when the copy code button is present

- _includes/docs/user-guide/device-connectivity-status.md
The documentation updated for Device Connectivity Events page
```bash
```
> Documentation page for activity reporting strategies

- _includes/integrators.json
Added **Absolute Motion** distributor
```bash
```
> Distributors page. Added Absolute Motion distributor

- _includes/docs/pe/user-guide/install/coap-transport-config.md
- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/ie-executor-config.md
- _includes/docs/pe/user-guide/install/lwm2m-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/pe/user-guide/install/snmp-transport-config.md
- _includes/docs/pe/user-guide/install/vc-executor-config.md
- _includes/docs/user-guide/install/coap-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/lwm2m-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/snmp-transport-config.md
- _includes/docs/user-guide/install/vc-executor-config.md
- generate_config_pages.py
Added right-side content navigation menu for config pages, updated config pages
```bash
```
> Added right-side content navigation menu for config pages

- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Use postgres 15 version for edge upgrade instructions

- docs/iot-gateway/install/pip-installation.md
- docs/mqtt-broker/install/building-from-source.md
- docs/user-guide/install/building-from-source.md
- docs/user-guide/install/edge/building-from-source.md
Before fix:
After:
```bash
```
> Fixed copy code inside list

- _includes/docs/devices-library/blocks/single-board-computers/thingsboard-synchronize-device-state-using-attribute-requests-block.md
- _includes/docs/devices-library/blocks/single-board-computers/update-shared-attributes-block.md
- _includes/head-header.html
- _includes/templates/install/windows-memory-on-slow-machines.md
- _includes/templates/iot-gateway/mqtt-converter-bytes-config.md
- _includes/templates/iot-gateway/mqtt-converter-custom-config.md
- _includes/templates/iot-gateway/mqtt-converter-json-config.md
- _includes/templates/iot-gateway/request-converter-json-config.md
- _includes/templates/iot-gateway/rest-converter-json-config.md
- docs/iot-gateway/config/modbus.md
- docs/iot-gateway/config/opc-ua.md
- docs/iot-gateway/config/rest.md
- docs/iot-gateway/guides/how-to-use-gateway-shell.md
- docs/services/services.sass
- docs/user-guide/install/edge/rhel.md
- docs/user-guide/install/pe/windows.md
Fixed license server page:
Before:
After:
Remove unnecessary <br>
Before:
After:
Fixed Services page:
Before:
After:
Remove unnecessary tabs:
Before:
After:
Added copy code for all code block on this page: '/docs/iot-gateway/guides/how-to-use-gateway-shell/'
```bash
```
> Fixed license server page and fixes for docs

- _includes/head-header.html
- _includes/templates/iot-gateway/remote-creating-connector-mqtt.md
- _includes/templates/prerequisites.md
- _sass/_base.sass
> Fixed link for products and align github button

- docs/iot-gateway/install/source-installation.md
> Updated IoT Gateway installation from sources guide

- docs/user-guide/install/rpi.md
Updated article headline, and unified it to all Raspberry Pi models.
Updated Java OpenJDK 11 installation instructions, the repository was added.
The rest of the article wasn't changed.
```bash
```
> Update Raspberry Pi installation instruction

- _includes/docs/pe/user-guide/integrations/send-data-external-mqtt-brokers.md
- _includes/docs/user-guide/contribution/widgets-development-before-3.0.md
- _includes/docs/user-guide/rule-engine-2-0/tutorials/integration-with-telegram-bot.md
- docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial.md
- docs/user-guide/rule-engine-2-0/tutorials/send-email.md
Before fix:
After:
```bash
```
> Fixed tables width

- docs/iot-gateway/install/deb-installation.md
- docs/iot-gateway/install/rpm-installation.md
> Update Install ThingsBoard IoT Gateway as package guide

- docs/iot-gateway/install/deb-installation.md
- docs/iot-gateway/install/rpm-installation.md
> Updated Prerequisites section of the Install TB IoT Gateway as package guide

- _config.yml
- _includes/trendz-wizard.html
- _includes/trendz-wizard.sass
- docs/trendz/install/docker-windows.md
- docs/trendz/install/docker.md
- docs/trendz/install/kubernetes.md
- docs/trendz/install/resources/1.11.0/trendz-centos-download.sh
- docs/trendz/install/resources/1.11.0/trendz-centos-installation.sh
- docs/trendz/install/resources/1.11.0/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.11.0/trendz-ubuntu-installation.sh
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/releases.md
- products/trendz/trendz.sass
> Trendz 1.11.0 release

- _includes/templates/iot-gateway/mqtt-connector-tls-security-config.md
> MQTT Connector Configuration. Updated Security subsection

- docs/iot-gateway/install/deb-installation.md
- docs/iot-gateway/install/rpm-installation.md
> Install ThingsBoard IoT Gateway as package guide. Updated docs for Ubuntu and CentOS or RHEL 

- _includes/head-header.html
- _layouts/plain.html
Have added Google Tag Manager on the site
```bash
```
> Add Google Tag Manager (GTM)

- _includes/head-header.html
- _layouts/plain.html
Reverts thingsboard/thingsboard.github.io#1421
> Revert "Add Google Tag Manager (GTM)"

- _includes/docs/devices-library/index.md
- _includes/docs/guides.md
- _includes/head-header.html
- _includes/trendz-wizard.html
- _layouts/plain.html
- _layouts/pricing.html
- js/script.js
* add test GTM code
* remove old google analytics
* mute programmable site events (temporary for repeat config in GTM)
> update GTM code and mute GA code events

- _includes/docs/mobile/release.md
- docs/paas/user-guide/custom-translation.md
- docs/pe/user-guide/custom-translation.md
Customer translation
Build and release ThingsBoard Mobile Application
> Mobile and custom translation docs: text editing

- _config.yml
- docs/edge/releases.md
- docs/pe/edge/releases.md
- docs/user-guide/install/edge/resources/3.6.4/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/3.6.4/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/3.6.4/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/3.6.4/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/resources/3.6.4/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/3.6.4/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/3.6.4/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/3.6.4/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Edge 3.6.4 Release

- _includes/head-header.html
- _layouts/thingsboard-paas.html
- _layouts/thingsboard-pe.html
- _sass/_base.sass
- home.sass
Achievement added for CE, PE and Pass.
```bash
```
> Update header for achievement

- _sass/_base.sass
> Fixed header buttons for opened burger menu

- _data/edge-pe/installation.yml
- _data/edge/installation.yml
- _includes/docs/edge/user-guide/install/how-to-change-config.md
- _includes/docs/pe/edge/user-guide/install/config.md
- docs/edge/user-guide/install/config.md
- docs/edge/user-guide/install/how-to-change-config.md
- docs/pe/edge/user-guide/install/config.md
- docs/pe/edge/user-guide/install/how-to-change-config.md
- generate_config_pages.py
The documentation updated for Edge configuration page. Added edge and edge-pe for generating_config_pages.
```bash
```
> Edge - update configuration page

- _includes/templates/install/ubuntu-queue-kafka.md
> Install ThingsBoard on Ubuntu guide. Update Kafka version

- _sass/_base.sass
- css/partners.sass
- partners/hardware/program/index.md
- partners/partner-program.sass
- use-cases/tank-level-monitoring.md
Fixed:
-Try it now button with hover effect.
- Fixed Use case 'Tank level monitoring' buttons
Before:
After:
- Add adaptive for partners program table
Before:
After:
```bash
```
> Fixed partner program table on mobile

- _includes/docs/user-guide/dashboards.md
- docs/paas/user-guide/dashboards.md
- docs/pe/user-guide/dashboards.md
- docs/user-guide/dashboards.md
> Dashboards guide. Changed locations of sections

- _includes/templates/iot-gateway/gateway-as-modbus-slave-serial-connection.md
- _includes/templates/iot-gateway/gateway-as-modbus-slave-tcpudp-connection.md
- _includes/templates/iot-gateway/modbus-serial-connection.md
- _includes/templates/iot-gateway/modbus-tcpudp-connection.md
- docs/iot-gateway/config/modbus.md
> Gateway Modbus Connector Configuration doc. Small text corrections 

- docs/iot-gateway/config/mqtt.md
> Gateway MQTT Connector Configuration doc. Small text corrections

- _includes/head-header.html
- _sass/_base.sass
- _sass/_docs.sass
Fixed PageSpeed Insights error
```bash
```
> Fixed menu indicator

- _includes/socials.html
> Remove Google Plus from socials

- _sass/_base.sass
- index.html
Fixed indicator for burger:
Before fix:
After fix:
Fixed loading resources:
eye-icon.svg and send-email-rule-chain.gif was loading from sources.
Fixed insights error to improve loading:
```bash
```
> Fixed insights error and fixed indicator for burger

- _data/paas/guides-data.yml
- _data/pe/guides-data.yml
> Updated links for the Guides page. PAAS and PE

- _includes/docs/user-guide/basic-mqtt.md
- docs/paas/user-guide/basic-mqtt.md
- docs/pe/user-guide/basic-mqtt.md
- docs/user-guide/basic-mqtt.md
> Basic MQTT authentication. Minor text corrections

- _includes/docs/devices-library/index.md
- _includes/docs/guides.md
- _includes/head-header.html
- _includes/trendz-wizard.html
- _layouts/plain.html
- _layouts/pricing.html
- js/script.js
Moving expression into a separate JS function
```bash
```
> Improvement for gtag

- _includes/head-header.html
- js/script.js
> Fixed call func before loading script

- docs/contact-us.md
> Fixed Contact Us form

- docs/iot-gateway/config/snmp.md
> IoT Gateway. SNMP Connector Configuration. Updated SNMP Connector documentation

- images/mqtt-broker/product/arrow-right.svg
- products/mqtt-broker/mqtt-broker.sass
> products/mqtt-broker fixed invisible arrows, minor adaptive improvements

- products/index.md
- products/products.sass
> MQTT Broker card for products page

- _includes/docs/user-guide/tbel.md
https://thingsboard-portal.atlassian.net/browse/PROD-3826
```bash
```
> Fix bug tbel date Example

- docs/iot-gateway/guides/how-to-use-get-set-rpc-methods.md
> Changed command in "How to use bult - in GET/SET RPC methods"

- _includes/docs/user-guide/basic-mqtt.md
> Basic MQTT authentication. Minor text corrections by Hlib

- docs/iot-gateway/install/source-installation.md
> IoT Gateway installation from sources. Updated guide

- _includes/docs/pe/user-guide/install/coap-transport-config.md
- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/ie-executor-config.md
- _includes/docs/pe/user-guide/install/lwm2m-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/pe/user-guide/install/snmp-transport-config.md
- _includes/docs/pe/user-guide/install/vc-executor-config.md
- _includes/docs/user-guide/install/coap-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/lwm2m-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/snmp-transport-config.md
- _includes/docs/user-guide/install/vc-executor-config.md
> Updated config pages for release 3.7

- blog/page/2/index.html
> paginaton fix

- docs/iot-gateway/config/modbus.md
- docs/user-guide/install/cluster/aws-microservices-setup.md
- docs/user-guide/install/pe/cluster/aws-microservices-setup.md
> Corrected grammatical errors on the "Microservices setup using AWS infrastructure" page

- _includes/docs/user-guide/contribution/rule-node-development.md
The documentation updated for Rule node development guide.
```bash
```
> Updated java version and documentation link

- _includes/integrators.json
> Added new distributor - REMATE

- _includes/integrators.json
> Added new distributor - Edgeware Technology Co Limited

- industries/industry40.md
> Edited Utvyakta web suite

- docs/user-guide/install/pe/resources/latest-pe/thingsboard-centos-download.sh
- docs/user-guide/install/pe/resources/latest-pe/thingsboard-centos-installation.sh
- docs/user-guide/install/pe/resources/latest-pe/thingsboard-ubuntu-download.sh
- docs/user-guide/install/pe/resources/latest-pe/thingsboard-ubuntu-installation.sh
- docs/user-guide/install/pe/upgrade-instructions.md
Added upgrade instructions from Community to Professional Edition.
```bash
```
> add CE to PE upgrade instructions

- blog/wp-content/themes/swyft-child/style.css
> Minor css fixes

- _includes/docs/devices-library/blocks/microcontrollers/camera-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/general-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/oled-example-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/thingsboard-arduino-library-install-block.md
- _includes/docs/devices-library/blocks/microcontrollers/thingsboard-send-rpc-to-device-block.md
- _includes/docs/devices-library/blocks/microcontrollers/thingsboard-synchronize-device-state-using-attribute-requests-block.md
- _includes/docs/devices-library/blocks/microcontrollers/thingsboard-update-shared-attributes-device-block.md
The documentation updated for device library examples.
```bash
```
> Updated code for device library examples due to new ThingsBoard Client SDK version

- _includes/docs/devices-library/blocks/ready-to-go-devices/am308-sensor-configuration-block.md
> AM308 Lorawan. Updated screenshots

- industries/industry40.md
> updated domain for Utvyakta

- _sass/_docs.sass
> Fixed Font Awasome icon on docs page

- pricing/index.md
> fix layout for Tb bundles pricing and for Trendz pricing

- docs/trendz/guide/analyze-building-energy-usage-and-carbon-emissions.md
The documentation updated for the guide of analyze-building-energy-usage-and-carbon-emissions
```bash
```
> Fixed typo in trendz guide

- _includes/integrators.json
> Added new partner - Corsinvest srl

- _includes/docs/user-guide/rule-engine-2-0/ce-filter-nodes.md
The documentation updated for the filter nodes.
```bash
```
> Filter nodes: updated doc

- _includes/templates/edge/create-tb-db-rhel.md
- _includes/templates/edge/install/ubuntu-db-postgresql.md
- _includes/templates/install/create-tb-db-rhel.md
- _includes/templates/install/create-tb-db.md
- _includes/templates/install/postgres-post-install.md
- docs/trendz/install/rhel.md
- docs/trendz/install/ubuntu.md
-Updated instructions to make them more accessible to an average user
-Added the ability to copy the code
```bash
```
> Improved description of Postgresql password and DB creation

- _includes/docs/user-guide/tbel.md
**1. change "int" to "var"**
**2. new methods number to string :**
- intToHex
- longToHex
- floatToHex
- doubleToHex
- intLongToString
**3. parse to Float/Double**
- parseHexToFloat
- parseLittleEndianHexToFloat
- parseBigEndianHexToFloat
- parseHexIntLongToFloat
- parseBytesIntToFloat -  https://github.com/thingsboard/thingsboard/pull/11296
- parseBytesLongToDouble
- parseBytesToFloat
- parseHexToDouble
- parseBigEndianHexToDouble
- parseLittleEndianHexToDouble
**4. new common methods:**
- encodeUri
- decodeUri
- raiseError
- isBinary
- isOctal
- isDecimal
- isHexadecimal
- validateClazzInArrayIsOnlyString return boolean
- printUnsignedBytes
- padStart - String.prototype.padStart() 
```
padStart("010011", 8, '0') return "00010011";
```
- padEnd - String.prototype.padEnd() 
``` …
```
> tbel: add new methods:

- _includes/docs/user-guide/scada.md
- _includes/docs/user-guide/scada/scada-symbols-dev-guide.md
- _includes/docs/user-guide/ui/layouts.md
ThingsBoard version changed from 3.7.1 to 3.8.0 in the following pages:
- SCADA overview;
- SCADA development guide;
- Layouts.
```bash
```
> ThingsBoard version changed from 3.7.1 to 3.8.0

- _includes/docs/pe/user-guide/integrations/remote-integrations.md
- _includes/docs/user-guide/tbel.md
- _includes/templates/edge/install/run-edge-install-windows.md
- _includes/templates/install/cassandra-ubuntu-install.md
- docs/trendz/install/windows.md
- docs/user-guide/install/building-from-source.md
- docs/user-guide/install/linux.md
- docs/user-guide/install/resources/java-centos-installation.sh
- docs/user-guide/install/resources/java-ubuntu-installation.sh
"java 11" replaced with "java 17"
```bash
```
> "java 11" update

- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
Updated config pages for 3.8 release
```bash
```
> Updated config pages for release 3.8

- _includes/docs/pe/user-guide/integrations/remote-integrations.md
- _includes/docs/user-guide/tbel.md
- _includes/templates/edge/install/run-edge-install-windows.md
- _includes/templates/install/cassandra-ubuntu-install.md
- docs/trendz/install/windows.md
- docs/user-guide/install/building-from-source.md
- docs/user-guide/install/linux.md
- docs/user-guide/install/resources/java-centos-installation.sh
- docs/user-guide/install/resources/java-ubuntu-installation.sh
Reverts thingsboard/thingsboard.github.io#1651
> Revert ""java 11" update"

- _config.yml
- _includes/docs/mobile/getting-started.md
> Updated mobile version to 1.3.0

- _includes/docs/mobile/getting-started.md
The documentation updated for mobile CE/PE Getting Started
```bash
```
> ThingsBoard platform / mobile versions mapping updated.

- _includes/docs/user-guide/tbel.md
> tbel: fix bug example: intToHex; longToHex

- blog/thingsboard-3-8-0-release/index.html
> Updated link in blog 3.8

- _includes/docs/user-guide/scada.md
- _includes/docs/user-guide/scada/scada-symbols-dev-guide.md
- docs/paas/user-guide/scada.md
- docs/pe/user-guide/scada.md
- docs/user-guide/scada.md
> SCADA.Correction of spelling errors

- _includes/templates/trndz-guides-banner.md
- docs/trendz/anomaly/anomaly-detection-overview.md
- docs/trendz/calculated-fields.md
- docs/trendz/embed-visuals.md
- docs/trendz/prediction-save-to-tb.md
- docs/trendz/states.md
- docs/trendz/view-settings.md
- products/trendz/index.md
> Fix trendz links

- _includes/templates/install/postgres-install-ubuntu.md
Updated ubuntu postgres installation
```bash
```
> Updated ubuntu postgres installation

- _data/paas-eu/docs-home.yml
- _includes/docs/devices-library/blocks/microcontrollers/camera-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/general-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/oled-example-code-to-program-block.md
- _includes/docs/devices-library/blocks/microcontrollers/rp2040-general-code-to-program-block.md
- _includes/docs/pe/solution-templates/air-quality-monitoring.md
- _includes/docs/pe/solution-templates/overview.md
- _includes/docs/pe/solution-templates/smart-irrigation.md
- _includes/docs/pe/solution-templates/smart-retail.md
- _includes/docs/pe/solution-templates/waste-management.md
- _includes/head-header.html
- _includes/product-selector.html
- docs/paas/eu/solution-templates/swimming-pool-scada-system.md
- products/paas/eu/what-is-thingsboard-cloud.md
> Hot-fixes for eu server

- _data/paas-eu/docs-home.yml
- _data/paas/docs-home.yml
- docs/paas/eu/user-guide/ui/chart-widget.md
- docs/paas/user-guide/ui/chart-widget.md
> Added link to Chart widgets doc (Cloud) for EU

- products/paas/eu/subscription.md
- products/paas/subscription.md
> Subscription page. Updated link to white labeling doc

- _includes/templates/edge/create-tb-db-rhel.md
- _includes/templates/install/postgres-install-rhel.md
- _includes/templates/install/postgres-install-ubuntu.md
- docs/trendz/install/rhel.md
- docs/user-guide/install/resources/3.8/install-postgres-contrib.sh
Updated postgres from 15 to 16
```bash
```
> Updated postgres from 15 to 16

- _includes/docs/user-guide/tbel.md
> tbel_fix_bug_example_test_invoke

- _includes/templates/integration/udp/udp-send-uplink-json.md
> Updated netcat command

- _includes/templates/ssl/certificates-leaf.md
> updated command to generate EC based key and certificate

- _data/guides-data.yml
- _includes/docs/user-guide/advanced-guides-for-working-with-dashboard/advanced-dashboard-guide-lesson-1.md
- _includes/templates/prerequisites-pe.md
- _includes/templates/prerequisites.md
> Added advanced guide to Guides CE page

- _includes/docs/user-guide/tbel.md
tbel: fix bug example: test invoke tbDate with ZoneId.systemDefault()
> tbe_doc_invok_ tbDate_ZoneId_systemDefault

- _includes/docs/user-guide/tbel.md
> Tbel_example tb_dateDefaultNewYork

- use-cases/smart-irrigation.md
- use-cases/tank-level-monitoring.md
- use-cases/waste-management.md
> Added links to the live demo

- _data/docs-home.yml
- _data/paas-eu/docs-home.yml
- _data/paas/docs-home.yml
- _data/pe/docs-home.yml
- docs/paas/eu/user-guide/oauth-2-support.md
- docs/paas/user-guide/oauth-2-support.md
- docs/pe/user-guide/oauth-2-support.md
- docs/user-guide/oauth-2-support.md
> Changed page title to OAuth 2.0

- _includes/docs/devices-library/blocks/basic/thingsboard-upload-example-dashboard-for-ws-202.md
- _includes/docs/user-guide/access-token.md
- _includes/docs/user-guide/ui/devices.md
- _includes/docs/user-guide/ui/mobile-qr-code.md
- docs/paas/eu/user-guide/access-token.md
- docs/paas/eu/user-guide/ui/devices.md
- docs/paas/user-guide/access-token.md
- docs/paas/user-guide/ui/devices.md
- docs/pe/user-guide/ui/devices.md
- docs/user-guide/rule-engine-2-0/tutorials/add-devices-to-group.md
- docs/user-guide/ui/devices.md
> Fixed broken links in the documentation

- _includes/templates/edge/use-cases/overview.md
- usage scenarios added to the article content. 
- improved existing descriptions
- corrected any possible grammar mistakes
/docs/edge/use-cases/overview/
/docs/pe/edge/use-cases/overview/
```bash
```
> Edge use cases overview

- use-cases/health-care.md
- use-cases/scada-health.sass
> Health care use case text content amendments

- docs/paas/eu/user-guide/rule-engine-2-0/tutorials/transform-incoming-telemetry.md
- docs/paas/user-guide/rule-engine-2-0/tutorials/transform-incoming-telemetry.md
- docs/pe/user-guide/rule-engine-2-0/tutorials/transform-incoming-telemetry.md
> Transform incoming telemetry documentation. Added redirection from /pe, /paas and /paas-eu pages to the main page

- installations/index.html
> Adding link parameter

- images/connectivity-paas-eu.svg
- images/connectivity-paas.svg
> Cross region links

- _includes/bubble-tabs.liquid
- _includes/carousel.liquid
- company/index.md
Optimizing performance by adding an loading lazy option, to the images
```bash
```
> loading lazy images

- _includes/docs/user-guide/tbel.md
> tbel_ bitWise_operations

- _config.yml
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.12.0/trendz-centos-download.sh
- docs/trendz/install/resources/1.12.0/trendz-centos-installation.sh
- docs/trendz/install/resources/1.12.0/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.12.0/trendz-ubuntu-installation.sh
- docs/trendz/install/trndz-upgrade-instructions-kubernetes.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/releases.md
> Trendz 1.12.0 release

- _includes/docs/user-guide/claiming-devices.md
> Basic claiming example python script fixed default endpoint.

- _includes/integrators.js
- _includes/integrators.json
> Added new partner - Moreton Systems Pty Ltd

- _includes/docs/pe/user-guide/install/coap-transport-config.md
- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/ie-executor-config.md
- _includes/docs/pe/user-guide/install/lwm2m-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/pe/user-guide/install/snmp-transport-config.md
- _includes/docs/pe/user-guide/install/vc-executor-config.md
- _includes/docs/user-guide/install/coap-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/lwm2m-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/snmp-transport-config.md
- _includes/docs/user-guide/install/vc-executor-config.md
Updated config pages for release 3.9
```bash
```
> Updated config pages for release 3.9

- _includes/docs/reference.md
- _includes/docs/user-guide/rule-engine-2-5/queues.md
> ThingsBoard architecture. Updated message queues section

- _includes/integrators.json
> Added new partner - Thingsnode Private Limited

- _includes/docs/mobile/getting-started.md
The documentation updated for Mobile Getting Started
```bash
```
> Updated mobile getting started doc to be aligned with TB 3.9.0 version.

- smart-farming.md
- smart-farming.sass
> added sections

- _includes/integrators.json
> Updated name for distributor - 4iG Nyrt

- _data/gw/docs-home.yml
- docs/iot-gateway/features-overview/report-strategy.md
Added documentation about report strategies on the gateway and removed deprecated features
```bash
```
> Added documentation about report strategies on the gateway and removed deprecated features

- use-cases/scada.md
Should be merged only after PaaS upgrade.
```bash
```
> [WIP] Updated link for scada dashboard

- _includes/docs/user-guide/ui/mobile-qr-code.md
> Fixed links in the Mobile application QR code documentation

- _includes/docs/user-guide/tbel.md
https://thingsboard-portal.atlassian.net/browse/PROD-5362
PRs
https://github.com/thingsboard/thingsboard/pull/12405
https://github.com/thingsboard/thingsboard-pe/pull/3166
- hexToBytesArray
```
var validInputList = "0x01752B0367FA000500010488FFFFFFFFFFFFFFFF33";
var validInputArray = "AABBCCDDEE";
msg.hexToBytes = hexToBytes(validInputList);
msg.hexToBytesArray = hexToBytesArray(validInputArray);
```
_return_ 
```
"hexToBytes": [1, 117, 43, 3, 103, -6, 0, 5, 0, 1, 4, -120, -1, -1, -1, -1, -1, -1, -1, -1, 51],
"hexToBytesArray": [-86, -69, -52, -35, -18]
```
- base64ToBytesList
```
msg.base64ToBytes =  base64ToBytes("Kkk=");
msg.base64ToBytesList =  base64ToBytesList("AQIDBAU=");
```
return 
```
"base64ToBytes": [42, 73],
"base64ToBytesList": [1, 2, 3, 4, 5]
```
The links will be checked …
> tbel: add hexToBytesArray, base64ToBytesList

- pricing/index.md
- pricing/pricing.sass
> Updated pricing for PE Self-managed perpetual licenses

- pricing/index.md
- pricing/pricing.sass
Reverts thingsboard/thingsboard.github.io#1808
> Revert "Updated pricing for PE Self-managed perpetual licenses"

- _layouts/pricing.html
- js/script.js
- pricing/index.md
- pricing/pricing.sass
**1.** This PR includes reverted changes from https://github.com/thingsboard/thingsboard.github.io/pull/1808, but with amendments.
before:
after:
**2.** Updated FAQ section
Now each product and solution has its own FAQ section.
To add or delete question, you have to find corresponding to product container
and corresponding to FAQ category sub-section.
Other steps stay same as before
before:
after:
```bash
```
> Pricing FAQ section redesign and content update, PE SM Perpetual pricing update

- _includes/trendz-wizard.html
Update coupon code for Trendz subscription plan
```bash
```
> Update Trendz coupon code

- _includes/docs/user-guide/contribution/widgets-development.md
- docs/paas/eu/user-guide/contribution/widgets-development.md
- docs/paas/user-guide/contribution/widgets-development.md
- docs/pe/user-guide/contribution/widgets-development.md
- docs/user-guide/contribution/widgets-development.md
Proofreading of the widget development guide.
> Proofreading of the widget development guide

- _includes/templates/edge/user-guide/start-upgrade.md
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/upgrade-instructions.md
upgrade instructions update
```bash
```
> upgrade instructions update

- docs/trendz/states.md
The documentation updated for Trendz state fields.
```bash
```
> Update Trendz states docs

- _includes/templates/iot-gateway/opcua-connector/device-attribute-updates-advanced-section.md
- _includes/templates/iot-gateway/opcua-connector/device-attribute-updates-basic-section.md
- _includes/templates/iot-gateway/opcua-connector/device-rpc-advanced-section.md
- _includes/templates/iot-gateway/opcua-connector/device-rpc-basic-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-advanced-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-attr-and-time-series-advanced-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-attr-and-time-series-basic-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-basic-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-data-mapping-advanced-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-data-mapping-basic-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-security-advanced-section.md
- _includes/templates/iot-gateway/opcua-connector/opcua-security-basic-section.md
- _includes/templates/iot-gateway/opcua-identity-username-config.md
- docs/iot-gateway/config/opc-ua.md
The documentation updated for OPC-UA connector.
```bash
```
> Updated OPC-UA connector docs

- _includes/templates/device-library/ready-to-go-devices/teltonika-rut955-imported-dashboard.md
- _includes/templates/device-library/ready-to-go-devices/temco-controls-t3e-6ct-configuring-gateway-advanced.md
- _includes/templates/device-library/ready-to-go-devices/temco-controls-t3e-6ct-configuring-gateway-basic.md
- _includes/templates/device-library/ready-to-go-devices/temco-controls-t3e-6ct-imported-dashboard.md
- _includes/templates/device-library/ready-to-go-devices/temco-controls-tstat10-configuring-gateway-advanced.md
- _includes/templates/device-library/ready-to-go-devices/temco-controls-tstat10-configuring-gateway-basic.md
- _includes/templates/device-library/ready-to-go-devices/temco-controls-tstat10-imported-dashboard.md
> Temco Tstat10 and Temco T3E-6CT devices. Minor edits of the documentation from Hleb

- _data/gw/docs-home.yml
- _data/gw/installation.yml
- _includes/templates/iot-gateway/knx-connector/data-secure-advanced.md
- _includes/templates/iot-gateway/knx-connector/ip-secure-advanced.md
- _includes/templates/iot-gateway/knx-connector/secure-tunneling-advanced.md
- docs/iot-gateway/config/knx.md
- docs/iot-gateway/what-is-iot-gateway.md
The documentation updated for KNX connector.
```bash
```
> Added KNX connector documentation

- _includes/docs/pe/user-guide/custom-translation.md
Affected page: [Custom translation](https://thingsboard.io/docs/pe/user-guide/custom-translation/)
```bash
```
> Fixed redirect link for custom translation page

- _data/host-constant.yml
- _includes/templates/provisioning/coap-access-token-credentials-type.md
- _includes/templates/provisioning/coap-without-credentials-type.md
- _includes/templates/provisioning/http-without-credentials-type.md
- _includes/templates/provisioning/mqtt-access-token-credentials-type.md
- _includes/templates/provisioning/mqtt-basic-credentials-type.md
- _includes/templates/provisioning/mqtt-without-credentials-type.md
- _includes/templates/provisioning/x509-certificate-credentials-type.md
> Fixed host name for device provisioning page

- docs/services/development-services/customers-full-reviews.md
Deleted duplicated text on the https://thingsboard.io/docs/services/development-services/customers-full-reviews/
Before: 
After:
```bash
```
> Deleted duplicated text on the page

- _includes/integrators.json
> Added new distributor - ELEMENT

- docs/contact-us.sass
> Fixed horizontal resize for textarea contact us form

- docs/trendz/background-jobs.md
Redundant signing key information was removed.
```bash
```
> Refactor Trendz background jobs documentation

- _data/edge-pe/installation.yml
- _data/edge/installation.yml
- _includes/templates/edge/install/memory-on-slow-edge-machines.md
- _includes/templates/edge/install/rpi-db-rpi-postgresql.md
- docs/user-guide/install/edge/installation-options.md
- docs/user-guide/install/edge/rpi.md
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/installation-options.md
- docs/user-guide/install/pe/edge/rpi.md
- docs/user-guide/install/pe/edge/upgrade-instructions.md
Edge Installation guide for Raspberry Pi for CE and PE
Upgrade instructions for CE and PE
```bash
```
> Edge on Rpi 

- products/license-server/billing-info.md
- products/license-server/index.md
- products/license-server/instance.md
- products/license-server/perpetual.md
- products/license-server/subscription.md
- products/license-server/user.md
> Delete user guide section from license portal page

- _includes/thingsboard-contacts.html
> Fixing the footer on the Our Company page

- docs/samples/smartico/elec-meter-lorawan/Electricity_Meter_LoRaWAN.md
> Electricity Three Phase Smart Meter "Smartico E307" telemetry upload. Edited title

- _layouts/pricing.html
- js/script.js
- pricing/index.md
- pricing/pricing.sass
> Pricing FAQ redesign

- _config.yml
- docs/trendz/configuration-properties.md
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.13.0/trendz-centos-download.sh
- docs/trendz/install/resources/1.13.0/trendz-centos-installation.sh
- docs/trendz/install/resources/1.13.0/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.13.0/trendz-ubuntu-installation.sh
- docs/trendz/install/trndz-upgrade-instructions-kubernetes.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/releases.md
> trendz release 1.13.0

- _config.yml
The documentation updated for Mobile Getting started. 
```bash
```
> The latest mobile version is updated to 1.5.0.

- _includes/accordion.liquid
- _includes/accordion.sass
- _includes/carousel.liquid
- docs/services/services.sass
- docs/services/trainings.md
> Fixed accordion "padding", fixed incorrect h1-4

- pricing/index.md
> PE Perpetual pricing update

- pricing/index.md
> PE Perpetual - Enterprise bundle: removed training sessions

- _includes/docs/pe/user-guide/integrations/loriot.md
- _includes/templates/integration/loriot/loriot-downlink-converter-config-java.md
- _includes/templates/integration/loriot/loriot-downlink-converter-config-tbel.md
> Loriot integration. Updated downlink converter

- docs/user-guide/install/pe/aws-marketplace.md
Updated AWS Marketplace instructions:
- Fixed broken and outdated links
- Added minimum instance requirements and Elastic IP recommendations
- Refactored backup, upgrade, logging instructions for clarity
- Updated pricing examples to reflect current instance types and license cost
```bash
```
> AWS Marketplace install guide fix

- _layouts/pricing.html
- pricing/index.md
- pricing/pricing.sass
> Pricing FAQ fixes

- _layouts/pricing.html
- js/script.js
> Pricing FAQ fixed copied question link not opening

- pricing/index.md
> Pricing FAQ hot-fixes

- _config.yml
- _includes/docs/edge/user-guide/install/config.md
- _includes/docs/pe/edge/user-guide/install/config.md
- docs/edge/releases.md
- docs/pe/edge/releases.md
- docs/user-guide/install/edge/resources/3.9.1/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/3.9.1/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/3.9.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/3.9.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/resources/3.9.1/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/3.9.1/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/3.9.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/3.9.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/upgrade-instructions.md
> Edge 3.9.1 Release

- _includes/templates/edge/user-guide/start-upgrade-pe.md
- _includes/templates/edge/user-guide/start-upgrade.md
- upgrade with docker bug fix 
```bash
```
> edge upgrade bug fix

- _includes/marketplace-style.css
- _includes/partner-script.js
- _includes/partner-style.css
- _includes/partners.json
- js/script.js
- partners/hardware/index.html
- partners/marketplace/index.html
> New partners page

- pricing/index.md
- products/trendz/index.md
The documentation updated for pricing page (add white-labeling info in Trendz subscription plans).
```bash
```
> Update Trendz pricing

- _includes/partners.json
> fixed partners.json

- _includes/docs/pe/user-guide/domains.md
- _includes/docs/user-guide/certificates.md
- _includes/templates/ssl/certificates-chain.md
- _includes/templates/ssl/certificates-leaf.md
- docs/paas/eu/user-guide/certificates.md
- docs/paas/user-guide/certificates.md
> Updated Domains and X.509 Certificate Based Authentication documentations

- _includes/integrators.json
> Updated info about Epithos Co Ltd distributor

- docs/reference/releases.md
Before fix:
After fix:
```bash
```
> Fixed release notes

- _sass/_base.sass
> Fixed header menu jumping of content after animation and aligned content horizontally

- _includes/usecase-nav.html
- _includes/usecase-nav.sass
> Use cases navigation drag and drop restore, items persist position on page switch

- _includes/usecase-nav.html
- services/development-services/development-services.sass
> Fixed use cases navigation from header menu

- _includes/docs/reference.md
- partners/marketplace/index.html
> Small ui changes

- products/thingsboard-pe/eula.md
> Update TB PE eula.md

- docs/user-guide/install/pe/aws-marketplace.md
Fix typos, general improvements and cleanup.
```bash
```
> Fix typos in aws marketplace guide

- _includes/docs/pe/user-guide/install/coap-transport-config.md
- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/ie-executor-config.md
- _includes/docs/pe/user-guide/install/lwm2m-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/pe/user-guide/install/snmp-transport-config.md
- _includes/docs/pe/user-guide/install/vc-executor-config.md
- _includes/docs/user-guide/install/coap-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/lwm2m-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/snmp-transport-config.md
- _includes/docs/user-guide/install/vc-executor-config.md
> Synced config pages with thingsboard.yml

- _includes/docs/user-guide/rule-engine-2-0/ce-action-nodes.md
The documentation updated for processing settings section in save time series and save attributes nodes.
```bash
```
> Remove mentions of modes in processing settings

- _includes/templates/install/docker-install.md
- _includes/templates/install/docker/docker-compose-setup-running.md
- _includes/templates/install/docker/docker-compose-setup-volumes.md
- _includes/templates/install/upgrade-docker-compose.md
- docs/user-guide/install/cluster/docker-compose-setup.md
- docs/user-guide/install/docker.md
- docs/user-guide/install/pe/cluster/docker-compose-setup.md
- docs/user-guide/install/pe/docker.md
The documentation updated for as per changes made here: https://github.com/thingsboard/thingsboard/pull/12821
```bash
```
> Update Docker install docs for OSX

- _config.yml
- _includes/docs/mobile/getting-started.md
The documentation updated for mobile getting started CE/PE. 
```bash
```
> The latest mobile version is updated to 1.6.0. TB Dart client 4.0.0.

- _includes/partners.json
- partners/hardware/index.html
> Updated Hardware Partners page

- docs/paas/eu/user-guide/widgets/map-widgets.md
> Fix maps widgets eu page

- iot-data-visualization.md
- iot-data-visualization.sass
> Visualization page fixes

- _data/carousel-collection/home-page-carousel.yml
- _includes/carousel.liquid
- _includes/cookie-consent.html
- _includes/customers-logo-section.liquid
- _includes/footer-social-networks.liquid
- _sass/_base.sass
- index.html
> Performance and seo improvement for GPSI

- iot-data-visualization.sass
- use-cases/environment-monitoring.md
> Environment monitoring scheme update, visualization page infinite widgets animation fixed

- _includes/docs/mqtt-broker/help.md
- docs/contact-us.md
> Contact us added 'TBMQ' subject and auto-select from the TBMQ 'Need help?' page

- _includes/docs/user-guide/tbel.md
https://thingsboard-portal.atlassian.net/browse/PROD-6141
Old: 
```
// Iterate through the map using entrySet()
for (Map.Entry<KeyType, ValueType> entry : map.entrySet()) {
```
New
```
// Iterate through the map
foreach(element : map.entrySet()){
```
```bash
```
> tbel refactoring for to forech

- _config.yml
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.13.1/trendz-centos-download.sh
- docs/trendz/install/resources/1.13.1/trendz-centos-installation.sh
- docs/trendz/install/resources/1.13.1/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.13.1/trendz-ubuntu-installation.sh
- docs/trendz/install/trndz-upgrade-instructions-kubernetes.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/releases.md
> Trendz 1.13.1 release - AI summary and prompts

- case-studies/index.md
> Fixed Super Bock group card title

- _includes/docs/devices-library/blocks/integrations/converters/basic/add-or-change-converter-block.md
- docs/paas/devices-library/ws202-pir-and-light-sensor.md
- docs/paas/eu/devices-library/ws202-pir-and-light-sensor.md
- docs/pe/devices-library/ws202-pir-and-light-sensor.md
> Devices library. WS202 PIR & Light Sensor. Updated uplink converter link for converter 20

- generate_config_pages.py
Changed #### to ## for the correct headings font-size in the config pages
```bash
```
> Change headings in config pages script

- use-cases/scada-energy-management.md
- use-cases/scada-oil-and-gas-drilling-system.md
Updated links to SCADA demos.
```bash
```
> Updated links to SCADA demos

- _includes/integrators.json
> added new partner - x-telia

- _includes/private-cloud-plan-calculator.html
- _includes/private-cloud-plan-calculator.sass
- docs/contact-us.md
- docs/contact-us.sass
- images/contact-us-bg.svg
- pricing/index.md
- pricing/pricing.sass
GTM for calculator:
```javascript
gtag("event", "private_cloud_calculator", {
"event_category": "Private Cloud Calculator",
'calculator_devices': parseInt(devicesInput.value) || 0,
'calculator_messages': parseInt(messagesInput.value) || 0,
'calculator_message_unit': messageUnitSelect.value,
'calculator_data_points': parseInt(dataPointsInput.value) || 0,
'calculator_retention_months': parseInt(retentionInput.value) || 0,
'calculator_addon_dev_envs': devEnvsCheckbox.checked,
'calculator_addon_test_envs': testEnvsCheckbox.checked,
'calculator_addon_mobile_app': mobileAppCheckbox.checked
});
``` 
```bash
docker run --rm -it …
```
> Private Cloud calculator GTM analytics, contact us form redesign

- _includes/integrators.json
> Change the name of the ECBM distributor to KIOTERA

- _includes/docs/devices-library/blocks/integrations/converters/basic/add-or-change-converter-block.md
- generate_lorawan_device_library_article.py
> Fixed Converter library branch name

- _layouts/pricing.html
- docs/contact-us.md
- pricing/index.md
- pricing/pricing.sass
> Switch from PE Cloud to Private Cloud button

- _includes/private-cloud-plan-calculator.html
- case-studies/index.md
- pricing/index.md
- pricing/pricing.sass
> Private cloud fixes, styles changed to show private cloud button on cloud page initially

- case-studies/nettra.md
- css/styles.sass
- pricing/pricing.sass
> Fixed PC plan calculator rendered on support pricing page

- _data/mqtt-broker/docs-home.yml
- _includes/private-cloud-plan-calculator.html
- _layouts/pricing.html
- docs/mqtt-broker/subscription.md
- pricing/index.md
- pricing/pricing.sass
> TBMQ pricing

- docs/contact-us.md
- docs/mqtt-broker/subscription.md
- pricing/index.md
> TBMQ pricing, FAQ amendments

- pricing/index.md
> Private Cloud FAQ amendments

- _includes/private-cloud-plans.json
> Private Cloud - Scale plan max data points increase

- _includes/devicelibrary.html
- _includes/devices.liquid
- docs/devices-library.sass
- js/script.js
> Fix of the devices library filter bug

- _includes/docs/user-guide/scada/scada-symbols-dev-guide.md
Merge with: [#13529](https://github.com/thingsboard/thingsboard/pull/13529)
```bash
```
> Update ScadaSymbolApi with new api for unit conversion

- _includes/docs/user-guide/calculated-fields.md
> Calculated fields documentation. Added note about permissions

- docs/user-guide/install/installation-options.sass
> Centring installations

- _includes/docs/devices-library/guides/macro-bluetooth-gateway.md
- _includes/docs/devices-library/guides/micro-bluetooth-gateway.md
- docs/devices-library/cat1-macro-bluetooth-gateway.md
- docs/paas/devices-library/cat1-container-tracker.md
- docs/paas/devices-library/cat1-macro-bluetooth-gateway.md
- docs/paas/eu/devices-library/cat1-container-tracker.md
- docs/paas/eu/devices-library/cat1-macro-bluetooth-gateway.md
- docs/pe/devices-library/cat1-container-tracker.md
- docs/pe/devices-library/cat1-macro-bluetooth-gateway.md
> Updated Lansitec devices information in Devices Library

- _includes/docs/reference/mqtt-sparkplug-api.md
> Sparkplug 3 0

- pricing/index.md
- pricing/pricing.sass
> PE self managed perpetual Add-ons

- _includes/footer.html
- _includes/head-header.html
- _sass/_base.sass
> Pricing and Try it now buttons swap

- _config.yml
- docs/trendz/install/docker.md
- docs/trendz/install/resources/1.13.2/trendz-centos-download.sh
- docs/trendz/install/resources/1.13.2/trendz-centos-installation.sh
- docs/trendz/install/resources/1.13.2/trendz-ubuntu-download.sh
- docs/trendz/install/resources/1.13.2/trendz-ubuntu-installation.sh
- docs/trendz/install/trndz-upgrade-instructions-kubernetes.md
- docs/trendz/install/trndz-upgrade-instructions.md
- docs/trendz/releases.md
> Trendz 1.13.2 release

- _includes/contact-us-banner.liquid
- _includes/private-cloud-plan-calculator.html
- _includes/private-cloud-plan-calculator.sass
- _sass/_base.sass
> Private cloud calculator payload enhancement

- _includes/contact-us-card.liquid
- _includes/contact-us-card.sass
- _includes/private-cloud-plan-calculator.html
- index.html
- iot-use-cases.md
- pricing/index.md
> Private Cloud calculator: data retention for each device profile

- _includes/templates/install/upgrade-docker-compose.md
> clarify "fromVersion" usage in Docker Compose upgrade guide

- _includes/docs/devices-library/blocks/ready-to-go-devices/air-temperature-and-humidity-sensor-configuration-block.md
- _includes/docs/devices-library/blocks/ready-to-go-devices/positioning-water-leak-sensor-configuration-block.md
- _includes/docs/devices-library/blocks/ready-to-go-devices/soil-moisture-sensor-configuration-block.md
- _includes/docs/devices-library/guides/16a-switch-and-power-meter-compact-16a-relay-and-electricity-meter.md
- _includes/docs/devices-library/guides/air-temperature-and-humidity-sensor.md
- _includes/docs/devices-library/guides/co2-display-lite-temperature-and-humidity-sensor.md
- _includes/docs/devices-library/guides/positioning-water-leak-sensor.md
- _includes/docs/devices-library/guides/soil-moisture-sensor.md
- _includes/docs/devices-library/guides/vicki-smart-radiator-thermostat.md
> Device library fixes

- _data/guides-data.yml
- _includes/docs/getting-started-guides/helloworld-pe.md
- _includes/templates/prerequisites-pe.md
- _includes/templates/prerequisites.md
- docs/getting-started-guides/helloworld-pe.md
- docs/getting-started-guides/helloworld.md
> Getting Started CE guide. Added video link to CE Getting Started guide

- _data/products.yml
- _includes/find-product-page.html
> Adding docs prefix to the products

- _includes/docs/user-guide/tbel.md
TBEL allows you to create Sets. We use our own implementation of the Set to control memory usage of the script.
That is why TBEL allows only inline creation of sets. 
In TBEL there are two supported ways to create a Set as ExecutionLinkedHashSet
```bash
```
> tbel - add sets

- _includes/docs/reference/lwm2m-api.md
- docs/paas/eu/reference/lwm2m-api.md
- docs/paas/reference/lwm2m-api.md
- docs/pe/reference/lwm2m-api.md
- docs/reference/lwm2m-api.md
> Lwm2m_ThingsBoard_Demo_Client

- _data/hardware-partners.yml
- _includes/hardware-partners-cards.liquid
- partners/hardware/index.html
> Fix of Makerfabs carousel

- _data/hardware-partners.yml
- images/partners/weinzierl-logo.svg
- partners/hardware/index.html
> Hardware Partner. Added Weinzierl Engineering GmbH

- _config.yml
- _includes/docs/edge/user-guide/install/config.md
- _includes/docs/pe/edge/user-guide/install/config.md
- _includes/templates/edge/install/compatibility-warning-version.md
- docs/edge/releases.md
- docs/edge/roadmap.md
- docs/pe/edge/releases.md
- docs/pe/edge/roadmap.md
- docs/user-guide/install/edge/resources/4.0.1/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/4.0.1/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/4.0.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/4.0.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/resources/4.1/tb-edge-centos-download.sh
- docs/user-guide/install/edge/resources/4.1/tb-edge-centos-installation.sh
- docs/user-guide/install/edge/resources/4.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/edge/resources/4.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/edge/upgrade-instructions.md
- docs/user-guide/install/pe/edge/resources/4.0.1/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/4.0.1/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/4.0.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/4.0.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/resources/4.1/tb-edge-centos-download.sh
- docs/user-guide/install/pe/edge/resources/4.1/tb-edge-centos-installation.sh
- docs/user-guide/install/pe/edge/resources/4.1/tb-edge-ubuntu-download.sh
- docs/user-guide/install/pe/edge/resources/4.1/tb-edge-ubuntu-installation.sh
- docs/user-guide/install/pe/edge/upgrade-instructions.md
- upgrade instructions for edge v4.1
- roadmap (v4.2 and upcoming releases)
- release notes 
- added links to contributors on GitHub
- website version updated
> 4.1 - docs update

- pricing/index.md
Updatet text for **What support is included in my subscription?**
https://thingsboard.io/pricing/?product=thingsboard-pe&faqSection=supportAndAssistance#pe-pay-as-you-go-support-included
and 
https://thingsboard.io/pricing/?product=thingsboard-cloud&faqSection=supportAndAssistance#tb-cloud-support-included
```bash
```
> ThingsBoard Pricing. Updated text for Cloud and Self managed plan

- docs/iot-gateway/config/mqtt.md
> Replaced example configuration file

- _data/docs-home.yml
- _data/paas-eu/docs-home.yml
- _data/paas/docs-home.yml
- _data/pe/docs-home.yml
- _includes/docs/user-guide/templatization.md
The documentation updated for Templatization page
```bash
```
> Add docs for new all data and all metadata templates to templatization page

- cookie-policy/index.md
> Updated cookie policy page

- _data/hardware-partners.yml
- _includes/docs/devices-library/guides/eg8200-gateway.md
> ThingsBoard Hardware Partners. Updated IOTRouter partner info

- _includes/docs/user-guide/device-profiles.md
> Proto schema attribute update for MQTT and CoAP

- _includes/templates/iot-gateway/upgrade-instructions/cent-rhel-server.md
- _includes/templates/iot-gateway/upgrade-instructions/docker.md
- _includes/templates/iot-gateway/upgrade-instructions/python-pip.md
- _includes/templates/iot-gateway/upgrade-instructions/ubuntu-raspberry.md
- docs/iot-gateway/install/deb-installation.md
- docs/iot-gateway/install/rpm-installation.md
- docs/iot-gateway/install/upgrade-instructions.md
The documentation updated for Gateway installation and upgrade instructions.
```bash
```
> Updated Gateway installation and upgrade instructions

- _data/api.yml
- _data/edge-pe/api.yml
- _data/edge/api.yml
- _data/paas-eu/api.yml
- _data/paas/api.yml
- _data/pages_info.yml
- _data/pe/api.yml
- _includes/docs/reference/mcp-server.md
- docs/edge/reference/mcp-server.md
- docs/paas/eu/reference/mcp-server.md
- docs/paas/reference/mcp-server.md
- docs/pe/edge/reference/mcp-server.md
- docs/pe/reference/mcp-server.md
- docs/reference/mcp-server.md
The documentation updated for ThingsBoard MCP Server into API section.
Added into:
* Community Edition
* Professional Edition
* Cloud
* Cloud  EU
* Edge
* Edge PE
```bash
```
> Added ThingsBoard MCP Server to API

- _includes/docs/pe/user-guide/install/coap-transport-config.md
- _includes/docs/pe/user-guide/install/core-rule-engine-config.md
- _includes/docs/pe/user-guide/install/http-transport-config.md
- _includes/docs/pe/user-guide/install/ie-executor-config.md
- _includes/docs/pe/user-guide/install/lwm2m-transport-config.md
- _includes/docs/pe/user-guide/install/mqtt-transport-config.md
- _includes/docs/pe/user-guide/install/snmp-transport-config.md
- _includes/docs/pe/user-guide/install/vc-executor-config.md
- _includes/docs/user-guide/install/coap-transport-config.md
- _includes/docs/user-guide/install/core-rule-engine-config.md
- _includes/docs/user-guide/install/http-transport-config.md
- _includes/docs/user-guide/install/lwm2m-transport-config.md
- _includes/docs/user-guide/install/mqtt-transport-config.md
- _includes/docs/user-guide/install/snmp-transport-config.md
- _includes/docs/user-guide/install/vc-executor-config.md
> Updated config pages for 4.2 release

- _includes/docs/getting-started-guides/connectivity.md
Add alt text to "Device Connectivity" pages with SVG HTML objects to ensure website accessibility.
```bash
```
> Add alt text for connectivity diagrams SVGs

- _data/guides-data.yml
- _data/paas-eu/guides-data.yml
- _data/paas/guides-data.yml
- _data/pe/guides-data.yml
> Guides page. Updated Data visualization block

- products/paas/index.md
- products/thingsboard-pe/index.md
> Updated outdated link to Reporting doc

- _includes/docs/user-guide/alarms.md
Remove bad practice and provide up to date method instead
```bash
```
> Clarify alarm creation in "working with alarms doc"

- _includes/docs/user-guide/dashboards.md
This PR rephrases the hint about making entities public to make it clearer and easier for users to understand.
```bash
```
> Rephrase doc for public dashboard

- _includes/docs/user-guide/attributes.md
I expanded the description of Attribute types and Shared attributes, making the text clearer and easier to understand by adding practical examples.
```bash
```
> clarify attribute type description

- _includes/docs/user-guide/ui/customers-pe.md
- _includes/docs/user-guide/ui/customers.md
- docs/paas/eu/user-guide/ui/customers.md
- docs/paas/user-guide/ui/customers.md
- docs/pe/user-guide/ui/customers.md
- docs/user-guide/ui/customers.md
> Customers page. Updated for chat

- _includes/docs/user-guide/ui/devices.md
The documentation updated for [Devices](https://thingsboard.io/docs/paas/user-guide/ui/devices/#manage-device-owner-and-groups)
```bash
```
> Improve doc device owners

- _includes/docs/faq.md
This PR adds a new frequently asked question about the ThingsBoard logo, along with the corresponding answer.
```bash
```
> Add FAQ entry about white labeling

- _data/docs-home.yml
- _data/paas-eu/docs-home.yml
- _data/paas/docs-home.yml
- _data/pe/docs-home.yml
> change Nodes to Rules Nodes in docs menu

- docs/iot-gateway/install/deb-installation.md
- docs/trendz/install/rhel.md
- docs/trendz/install/ubuntu.md
- docs/trendz/install/windows.md
- docs/user-guide/install/building-from-source.md
- docs/user-guide/install/edge/building-from-source.md
- docs/user-guide/install/edge/deb-installation.md
- docs/user-guide/install/edge/rhel.md
- docs/user-guide/install/edge/windows.md
- docs/user-guide/install/pe/edge/deb-installation.md
- docs/user-guide/install/pe/edge/rhel.md
- docs/user-guide/install/pe/edge/windows.md
- docs/user-guide/install/pe/ubuntu.md
- docs/user-guide/install/ubuntu.md
Updated the operating system versions in the installation documentation for our products
```bash
```
> Actualization-of-supported-OS-versions-2

- _data/edge-pe/installation.yml
- _data/edge/installation.yml
- _data/installation.yml
- _data/pe/installation.yml
- _data/trendz/installation.yml
- docs/user-guide/install/installation-options.md
- docs/user-guide/install/pe/installation-options.md
- installations/index.html
- js/script.js
- products/license-server/index.md
- products/thingsboard-pe/index.md
- products/thingsboard-pe/install.md
- services/consulting.md
> Fixed spelling mistakes

- docs/paas/eu/subscription.md
- docs/paas/subscription.md
ThingsBoard Cloud Subscription Plans definition page. 
Added a table with **calculated fields** limits.
```bash
```
> ThingsBoard Cloud Subscription Plans definition page. Added a table with Calculated fields limits.

- docs/private-cloud/subscription.md
Actualized the database information for the Launch plan, now correctly specified as SQL + NoSQL.
```bash
```
> Actualization-of-Additional-Features-Launch
